name: poker_venv
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0=py35_1
- backports.weakref=1.0rc1=py35_1
- bleach=1.5.0=py35_0
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py35_0
- cffi=1.11.2=py35_0
- chardet=3.0.4=py35_0
- colorama=0.3.9=py35_0
- cryptography=2.1.4=py35_0
- cycler=0.10.0=py35_0
- expat
- freetype
- html5lib
- icu
- idna
- jpeg
- libflang
- libiconv
- libpng
- libxcb
- libxml2
- lmfit
- lockfile
- markdown
- matplotlib
- mock
- msgpack-python
- openblas
- openssl
- packaging
- pandas
- pbr
- pcre
- progress
- protobuf
- pycparser
- pyopenssl
- pyparsing
- pyqt5
- pysocks=1.6.7=py35_0
- python=3.5.4=3
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2
- requests=2.18.4=py35_1
- setuptools=38.4.0=py35_0
- sip=4.18=py35_1
- six=1.10.0=py35_1
- sqlite=3.20.1=vc14_2
- tensorflow=1.3.0=py35_0
- tk=8.6.7=vc14_0
- tornado=4.5.2=py35_0
- urllib3=1.22=py35_0
- werkzeug=0.12.2=py_1
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib
- cachecontrol=0.12.3=py35_0
- configobj=5.0.6=py35_0
- numpy
- pip
- scipy=1.0.0=py35h75710e8_0
- pip:
  - backports.functools-lru-cache==1.4
  - opencv-python==3.4.0.12
  - pillow
  - pymongo
  - pypiwin32
  - pyqt5
  - pytesseract
  - pyvbox
  - tesseract
  - win-inet-pton
  - xlrd

