name: poker_venv
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0=py35_1
- backports.weakref=1.0rc1=py35_1
- bleach=1.5.0=py35_0
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py35_0
- cffi=1.11.2=py35_0
- chardet=3.0.4=py35_0
- colorama=0.3.9=py35_0
- cryptography=2.1.4=py35_0
- cycler=0.10.0=py35_0
- expat
- freetype
- html5lib
- icu
- idna
- jpeg
- libiconv
- libxcb
- libxml2
- lmfit
- lockfile
- markdown
- mock
- msgpack-python
- numpy
- openblas
- openssl
- packaging
- pandas
- pbr
- pcre
- progress=1.3=py35_0
- protobuf
- pycparser=2.18=py35_0
- pyopenssl=17.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pysocks=1.6.7=py35_0
- python=3.5.4=3
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt
- requests=2.18.4=py35_1
- scipy
- six=1.10.0=py35_1
- sqlite
- tensorflow=1.3.0=py35_0
- tk
- tornado=4.5.2=py35_0
- urllib3=1.22=py35_0
- werkzeug=0.12.2=py_1
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib
- cachecontrol=0.12.3=py35_0
- configobj=5.0.6=py35_0
- intel-openmp
- libpng
- matplotlib
- mkl
- pip=9.0.1=py35_0
- pyqt
- sip
- webencodings
- pip:
  - altgraph==0.14
  - future==0.16.0
  - h5py==2.7.1
  - keras==2.0.8
  - macholib==1.8
  - olefile==0.44
  - opencv-python==3.3.0.10
  - pefile==2017.9.3
  - pillow==4.3.0
  - pyinstaller==3.3
  - pymongo==3.5.1
  - pyqt5==5.9
  - pytesseract==0.1.7
  - pyvbox==1.2.0
  - pyyaml==3.12
  - win-inet-pton==1.0.1
  - xlrd==1.1.0

