name: poker_venv
channels:
- defaults
dependencies:
- backports=1.0
- bleach=2.1.2
- configobj=5.0.6
- cycler=0.10.0
- freetype=2.8
- intel-openmp=2018.0.0
- jpeg=9b
- libpng=1.6.34
- libprotobuf=3.4.1
- libxml2=2.9.7
- lockfile=0.12.2
- markdown=2.6.9
- matplotlib=2.1.2
- mkl=2018.0.1
- mock=2.0.0
- msgpack-python=0.5.1
- numpy=1.12.1
- openssl=1.0.2n
- packaging=16.8
- pandas=0.22.0
- pbr=3.1.1
- pcre=8.41
- pip=9.0.1
- progress=1.3
- protobuf=3.4.1
- pycparser=2.18
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyqt=5.6.0
- pysocks=1.6.7
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- qt=5.6.2
- requests=2.18.4
- scipy=1.0.0
- setuptools=38.4.0
- sip=4.18.1
- six=1.11.0
- sqlite=3.22.0
- tensorflow=1.1.0
- tk=8.6.7
- tornado=4.5.3
- urllib3=1.22
- vc=14
- vs2015_runtime=14.0.25420
- webencodings=0.5.1
- werkzeug=0.14.1
- wheel=0.30.0
- win_inet_pton=1.0.1
- wincertstore=0.2
- xz=5.2.3
- zlib=1.2.11
- pip:
  - lmfit==0.9.7
  - opencv-python==3.4.0.12
  - pillow==5.0
  - pymongo==3.6
  - pypiwin32
  - pytesseract==0.2
  - pyvbox==1.2
  - svgwrite==1.1.12
  - tesseract==0.1.3
  - win-inet-pton==1.0
  - xlrd==1.1

