'''
This class is used to handle the strategies.xml file, which contains the parameters that are generated by the
genetic algorithm. They are mainly linked to how agressive or conservative the pokerbot should play in different
circumstances or game stages.
'''

import xml.etree.ElementTree as xml
from copy import deepcopy
import re


class XMLHandler(object):
    def __init__(self, filename):
        self.XML_entries_list1 = dict()
        self.filename = filename

    def read_XML(self,strategy_override=''):
        self.tree = xml.parse(self.filename)
        self.root = self.tree.getroot()


        self.current_strategy = self.root.find('CurrentStrategy')
        selected_strategy=self.current_strategy.text if strategy_override=='' else strategy_override

        for self.XML_entry in self.root.findall('Strategy'):
            if self.XML_entry.get('name') == selected_strategy:
                for child in self.XML_entry:
                    self.XML_entries_list1[child.tag] = child

        self.XML_entries_list2 = deepcopy(self.XML_entries_list1)

        for e in self.XML_entries_list2:
            self.XML_entries_list2[e].set('updated', 'False')

        self.modified = False
        self.Template = self.current_strategy.text

    def modify_XML(self, elementName, change):
        self.XML_entries_list2[elementName].text = str(
            round(float(self.XML_entries_list2[elementName].text) + change, 2))
        self.XML_entries_list2[elementName].set('updated', str(change))
        self.modified = True

    def save_XML(self):
        r = re.compile("([a-zA-Z]+)([0-9]+)")
        m = r.match(self.current_strategy.text)
        stringPart = m.group(1)
        numberPart = int(m.group(2))
        numberPart += 1
        self.new_strategy_name = stringPart + str(numberPart)
        self.current_strategy.text = self.new_strategy_name
        newElement = xml.Element('Strategy')
        newElement.set('name', self.new_strategy_name)
        self.root.append(newElement)
        for child in self.XML_entry:
            newElement.append(self.XML_entries_list2[child.tag])

            self.tree.write(self.filename)
            self.XML_entries_list1 = deepcopy(self.XML_entries_list2)

        self.Template = self.current_strategy.text


if __name__ == '__main__':
    XML = XMLHandler('strategies.xml')
    XML.read_XML()
    # XML.modify_XML('RiverCallPower',-1)
    pass
