# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pokerbot(object):
    def setupUi(self, Pokerbot):
        Pokerbot.setObjectName("Pokerbot")
        Pokerbot.resize(617, 713)
        Pokerbot.setMinimumSize(QtCore.QSize(617, 713))
        Pokerbot.setMaximumSize(QtCore.QSize(617, 713))
        font = QtGui.QFont()
        font.setPointSize(12)
        Pokerbot.setFont(font)
        Pokerbot.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Pokerbot)
        self.centralwidget.setObjectName("centralwidget")
        self.last_decision = QtWidgets.QLabel(self.centralwidget)
        self.last_decision.setGeometry(QtCore.QRect(330, 230, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.last_decision.setFont(font)
        self.last_decision.setAutoFillBackground(False)
        self.last_decision.setFrameShape(QtWidgets.QFrame.Panel)
        self.last_decision.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.last_decision.setScaledContents(False)
        self.last_decision.setAlignment(QtCore.Qt.AlignCenter)
        self.last_decision.setIndent(-1)
        self.last_decision.setObjectName("last_decision")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(470, 270, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_pause.setFont(font)
        self.button_pause.setObjectName("button_pause")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 40, 201, 181))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 510, 301, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vLayout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vLayout3.setObjectName("vLayout3")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.widget.setObjectName("widget")
        self.vLayout3.addWidget(self.widget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 301, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout.setObjectName("vLayout")
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.vLayout.addWidget(self.widget_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(320, 320, 291, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vLayout2.setObjectName("vLayout2")
        self.widget_4 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_4.setObjectName("widget_4")
        self.vLayout2.addWidget(self.widget_4)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(20, 270, 291, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.button_log_analyser = QtWidgets.QPushButton(self.centralwidget)
        self.button_log_analyser.setEnabled(False)
        self.button_log_analyser.setGeometry(QtCore.QRect(20, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_log_analyser.setFont(font)
        self.button_log_analyser.setObjectName("button_log_analyser")
        self.button_resume = QtWidgets.QPushButton(self.centralwidget)
        self.button_resume.setEnabled(False)
        self.button_resume.setGeometry(QtCore.QRect(330, 270, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_resume.setFont(font)
        self.button_resume.setObjectName("button_resume")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(330, 40, 198, 181))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(220, 40, 91, 181))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.equity = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.equity.setObjectName("equity")
        self.verticalLayout_3.addWidget(self.equity)
        self.calllimit = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.calllimit.setObjectName("calllimit")
        self.verticalLayout_3.addWidget(self.calllimit)
        self.betlimit = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.betlimit.setObjectName("betlimit")
        self.verticalLayout_3.addWidget(self.betlimit)
        self.potsize = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.potsize.setObjectName("potsize")
        self.verticalLayout_3.addWidget(self.potsize)
        self.gamenumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.gamenumber.setObjectName("gamenumber")
        self.verticalLayout_3.addWidget(self.gamenumber)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(520, 40, 91, 181))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.assumed_players = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.assumed_players.setObjectName("assumed_players")
        self.verticalLayout_6.addWidget(self.assumed_players)
        self.required_mincall = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.required_mincall.setObjectName("required_mincall")
        self.verticalLayout_6.addWidget(self.required_mincall)
        self.required_minbet = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.required_minbet.setObjectName("required_minbet")
        self.verticalLayout_6.addWidget(self.required_minbet)
        self.zero_ev = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.zero_ev.setObjectName("zero_ev")
        self.verticalLayout_6.addWidget(self.zero_ev)
        self.winnings = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.winnings.setObjectName("winnings")
        self.verticalLayout_6.addWidget(self.winnings)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(320, 510, 291, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vLayout4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vLayout4.setObjectName("vLayout4")
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.widget_2.setObjectName("widget_2")
        self.vLayout4.addWidget(self.widget_2)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(20, 230, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.status.setFont(font)
        self.status.setFrameShape(QtWidgets.QFrame.Panel)
        self.status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.status.setScaledContents(False)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setIndent(-1)
        self.status.setObjectName("status")
        self.button_genetic_algorithm = QtWidgets.QPushButton(self.centralwidget)
        self.button_genetic_algorithm.setEnabled(False)
        self.button_genetic_algorithm.setGeometry(QtCore.QRect(180, 300, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_genetic_algorithm.setFont(font)
        self.button_genetic_algorithm.setObjectName("button_genetic_algorithm")
        self.button_strategy_editor = QtWidgets.QPushButton(self.centralwidget)
        self.button_strategy_editor.setEnabled(False)
        self.button_strategy_editor.setGeometry(QtCore.QRect(330, 300, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_strategy_editor.setFont(font)
        self.button_strategy_editor.setObjectName("button_strategy_editor")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(200, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.button_options = QtWidgets.QPushButton(self.centralwidget)
        self.button_options.setEnabled(False)
        self.button_options.setGeometry(QtCore.QRect(470, 300, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_options.setFont(font)
        self.button_options.setObjectName("button_options")
        Pokerbot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Pokerbot)
        self.statusbar.setObjectName("statusbar")
        Pokerbot.setStatusBar(self.statusbar)

        self.retranslateUi(Pokerbot)
        QtCore.QMetaObject.connectSlotsByName(Pokerbot)

    def retranslateUi(self, Pokerbot):
        _translate = QtCore.QCoreApplication.translate
        Pokerbot.setWindowTitle(_translate("Pokerbot", "Pokerbot"))
        self.last_decision.setText(_translate("Pokerbot", "Last Decision"))
        self.button_pause.setText(_translate("Pokerbot", "Pause"))
        self.label_2.setText(_translate("Pokerbot", "Equity (winning probability)"))
        self.label_3.setText(_translate("Pokerbot", "Final call limit"))
        self.label_4.setText(_translate("Pokerbot", "Final bet Limit"))
        self.label_5.setText(_translate("Pokerbot", "Pot Size"))
        self.label.setText(_translate("Pokerbot", "Hand number"))
        self.button_log_analyser.setText(_translate("Pokerbot", "Strategy Analyser"))
        self.button_resume.setText(_translate("Pokerbot", "Resume"))
        self.label_6.setText(_translate("Pokerbot", "Assumed players"))
        self.label_7.setText(_translate("Pokerbot", "Required minimum call"))
        self.label_8.setText(_translate("Pokerbot", "Required minimum bet"))
        self.label_9.setText(_translate("Pokerbot", "Zero EV Call"))
        self.label_10.setText(_translate("Pokerbot", "Last 500 hands return"))
        self.status.setText(_translate("Pokerbot", "Status"))
        self.button_genetic_algorithm.setText(_translate("Pokerbot", "Genetic Algorithm"))
        self.button_strategy_editor.setText(_translate("Pokerbot", "Strategy Editor"))
        self.label_11.setText(_translate("Pokerbot", "Dickreuter\'s Poker bot"))
        self.button_options.setText(_translate("Pokerbot", "Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pokerbot = QtWidgets.QMainWindow()
    ui = Ui_Pokerbot()
    ui.setupUi(Pokerbot)
    Pokerbot.show()
    sys.exit(app.exec_())

