# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_qt_ui_strategy_manager.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editor_form(object):
    def setupUi(self, editor_form):
        editor_form.setObjectName("editor_form")
        editor_form.resize(722, 748)
        editor_form.setMinimumSize(QtCore.QSize(722, 748))
        editor_form.setMaximumSize(QtCore.QSize(722, 748))
        self.gridLayout = QtWidgets.QGridLayout(editor_form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(editor_form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(editor_form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.Strategy = QtWidgets.QComboBox(editor_form)
        self.Strategy.setObjectName("Strategy")
        self.horizontalLayout_4.addWidget(self.Strategy)
        self.pushButton_save_current_strategy = QtWidgets.QPushButton(editor_form)
        self.pushButton_save_current_strategy.setEnabled(False)
        self.pushButton_save_current_strategy.setObjectName("pushButton_save_current_strategy")
        self.horizontalLayout_4.addWidget(self.pushButton_save_current_strategy)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(editor_form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_new_name = QtWidgets.QLineEdit(editor_form)
        self.lineEdit_new_name.setObjectName("lineEdit_new_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_new_name)
        self.pushButton_save_new_strategy = QtWidgets.QPushButton(editor_form)
        self.pushButton_save_new_strategy.setObjectName("pushButton_save_new_strategy")
        self.horizontalLayout_3.addWidget(self.pushButton_save_new_strategy)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(editor_form)
        self.tabWidget.setObjectName("tabWidget")
        self.Generic = QtWidgets.QWidget()
        self.Generic.setObjectName("Generic")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Generic)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_32 = QtWidgets.QLabel(self.Generic)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_27.addWidget(self.label_32)
        self.alwaysCallEquity = QtWidgets.QSlider(self.Generic)
        self.alwaysCallEquity.setMouseTracking(False)
        self.alwaysCallEquity.setToolTip("<html><head/><body><p>If the equity (winning probability) is higher than the value, the bot will never fold.</p></body></html>")
        self.alwaysCallEquity.setMinimum(1)
        self.alwaysCallEquity.setMaximum(100)
        self.alwaysCallEquity.setSingleStep(5)
        self.alwaysCallEquity.setPageStep(10)
        self.alwaysCallEquity.setOrientation(QtCore.Qt.Horizontal)
        self.alwaysCallEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.alwaysCallEquity.setTickInterval(0)
        self.alwaysCallEquity.setObjectName("alwaysCallEquity")
        self.verticalLayout_27.addWidget(self.alwaysCallEquity)
        self.gridLayout_3.addLayout(self.verticalLayout_27, 0, 0, 1, 1)
        self.lcdNumber_57 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_57.setObjectName("lcdNumber_57")
        self.gridLayout_3.addWidget(self.lcdNumber_57, 0, 1, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.Generic)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.BetPlusInc = QtWidgets.QSlider(self.Generic)
        self.BetPlusInc.setMouseTracking(False)
        self.BetPlusInc.setMinimum(1)
        self.BetPlusInc.setMaximum(20)
        self.BetPlusInc.setPageStep(1)
        self.BetPlusInc.setOrientation(QtCore.Qt.Horizontal)
        self.BetPlusInc.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.BetPlusInc.setObjectName("BetPlusInc")
        self.verticalLayout_14.addWidget(self.BetPlusInc)
        self.gridLayout_3.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.lcdNumber_56 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_56.setObjectName("lcdNumber_56")
        self.gridLayout_3.addWidget(self.lcdNumber_56, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.Generic)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.bullyDivider = QtWidgets.QSlider(self.Generic)
        self.bullyDivider.setMouseTracking(False)
        self.bullyDivider.setMinimum(1)
        self.bullyDivider.setMaximum(10)
        self.bullyDivider.setPageStep(1)
        self.bullyDivider.setOrientation(QtCore.Qt.Horizontal)
        self.bullyDivider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.bullyDivider.setObjectName("bullyDivider")
        self.verticalLayout_6.addWidget(self.bullyDivider)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        self.lcdNumber_58 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_58.setObjectName("lcdNumber_58")
        self.gridLayout_3.addWidget(self.lcdNumber_58, 2, 1, 1, 1)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_38 = QtWidgets.QLabel(self.Generic)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_33.addWidget(self.label_38)
        self.minBullyEquity = QtWidgets.QSlider(self.Generic)
        self.minBullyEquity.setMouseTracking(False)
        self.minBullyEquity.setMinimum(0)
        self.minBullyEquity.setMaximum(100)
        self.minBullyEquity.setPageStep(10)
        self.minBullyEquity.setOrientation(QtCore.Qt.Horizontal)
        self.minBullyEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.minBullyEquity.setObjectName("minBullyEquity")
        self.verticalLayout_33.addWidget(self.minBullyEquity)
        self.gridLayout_3.addLayout(self.verticalLayout_33, 3, 0, 1, 1)
        self.lcdNumber_55 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_55.setObjectName("lcdNumber_55")
        self.gridLayout_3.addWidget(self.lcdNumber_55, 3, 1, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_39 = QtWidgets.QLabel(self.Generic)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_34.addWidget(self.label_39)
        self.maxBullyEquity = QtWidgets.QSlider(self.Generic)
        self.maxBullyEquity.setMouseTracking(False)
        self.maxBullyEquity.setMinimum(0)
        self.maxBullyEquity.setMaximum(100)
        self.maxBullyEquity.setSingleStep(1)
        self.maxBullyEquity.setPageStep(10)
        self.maxBullyEquity.setOrientation(QtCore.Qt.Horizontal)
        self.maxBullyEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.maxBullyEquity.setObjectName("maxBullyEquity")
        self.verticalLayout_34.addWidget(self.maxBullyEquity)
        self.gridLayout_3.addLayout(self.verticalLayout_34, 4, 0, 1, 1)
        self.lcdNumber_59 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_59.setObjectName("lcdNumber_59")
        self.gridLayout_3.addWidget(self.lcdNumber_59, 4, 1, 1, 1)
        self.verticalLayout_432 = QtWidgets.QVBoxLayout()
        self.verticalLayout_432.setObjectName("verticalLayout_432")
        self.label_449 = QtWidgets.QLabel(self.Generic)
        self.label_449.setObjectName("label_449")
        self.verticalLayout_432.addWidget(self.label_449)
        self.minimumLossForIteration = QtWidgets.QSlider(self.Generic)
        self.minimumLossForIteration.setMouseTracking(False)
        self.minimumLossForIteration.setMinimum(0)
        self.minimumLossForIteration.setMaximum(100)
        self.minimumLossForIteration.setSingleStep(1)
        self.minimumLossForIteration.setPageStep(10)
        self.minimumLossForIteration.setOrientation(QtCore.Qt.Horizontal)
        self.minimumLossForIteration.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.minimumLossForIteration.setObjectName("minimumLossForIteration")
        self.verticalLayout_432.addWidget(self.minimumLossForIteration)
        self.gridLayout_3.addLayout(self.verticalLayout_432, 5, 0, 1, 1)
        self.lcdNumber_109 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_109.setObjectName("lcdNumber_109")
        self.gridLayout_3.addWidget(self.lcdNumber_109, 5, 1, 1, 1)
        self.verticalLayout_435 = QtWidgets.QVBoxLayout()
        self.verticalLayout_435.setObjectName("verticalLayout_435")
        self.label_452 = QtWidgets.QLabel(self.Generic)
        self.label_452.setObjectName("label_452")
        self.verticalLayout_435.addWidget(self.label_452)
        self.considerLastGames = QtWidgets.QSlider(self.Generic)
        self.considerLastGames.setMouseTracking(False)
        self.considerLastGames.setMinimum(100)
        self.considerLastGames.setMaximum(10000)
        self.considerLastGames.setSingleStep(1)
        self.considerLastGames.setPageStep(100)
        self.considerLastGames.setOrientation(QtCore.Qt.Horizontal)
        self.considerLastGames.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.considerLastGames.setTickInterval(100)
        self.considerLastGames.setObjectName("considerLastGames")
        self.verticalLayout_435.addWidget(self.considerLastGames)
        self.strategyIterationGames = QtWidgets.QSlider(self.Generic)
        self.strategyIterationGames.setMouseTracking(False)
        self.strategyIterationGames.setMinimum(100)
        self.strategyIterationGames.setMaximum(10000)
        self.strategyIterationGames.setSingleStep(1)
        self.strategyIterationGames.setPageStep(100)
        self.strategyIterationGames.setOrientation(QtCore.Qt.Horizontal)
        self.strategyIterationGames.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.strategyIterationGames.setTickInterval(100)
        self.strategyIterationGames.setObjectName("strategyIterationGames")
        self.verticalLayout_435.addWidget(self.strategyIterationGames)
        self.gridLayout_3.addLayout(self.verticalLayout_435, 6, 0, 2, 1)
        self.lcdNumber_112 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_112.setObjectName("lcdNumber_112")
        self.gridLayout_3.addWidget(self.lcdNumber_112, 6, 1, 1, 1)
        self.lcdNumber_113 = QtWidgets.QLCDNumber(self.Generic)
        self.lcdNumber_113.setObjectName("lcdNumber_113")
        self.gridLayout_3.addWidget(self.lcdNumber_113, 7, 1, 1, 1)
        self.tabWidget.addTab(self.Generic, "")
        self.PreFlop = QtWidgets.QWidget()
        self.PreFlop.setObjectName("PreFlop")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PreFlop)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_36 = QtWidgets.QLabel(self.PreFlop)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_31.addWidget(self.label_36)
        self.maxPotAdjustmentPreFlop = QtWidgets.QSlider(self.PreFlop)
        self.maxPotAdjustmentPreFlop.setMouseTracking(False)
        self.maxPotAdjustmentPreFlop.setMinimum(1)
        self.maxPotAdjustmentPreFlop.setMaximum(10)
        self.maxPotAdjustmentPreFlop.setPageStep(1)
        self.maxPotAdjustmentPreFlop.setOrientation(QtCore.Qt.Horizontal)
        self.maxPotAdjustmentPreFlop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.maxPotAdjustmentPreFlop.setObjectName("maxPotAdjustmentPreFlop")
        self.verticalLayout_31.addWidget(self.maxPotAdjustmentPreFlop)
        self.gridLayout_2.addLayout(self.verticalLayout_31, 9, 2, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_33 = QtWidgets.QLabel(self.PreFlop)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_28.addWidget(self.label_33)
        self.secondRoundAdjustmentPreFlop = QtWidgets.QSlider(self.PreFlop)
        self.secondRoundAdjustmentPreFlop.setMouseTracking(False)
        self.secondRoundAdjustmentPreFlop.setMinimum(0)
        self.secondRoundAdjustmentPreFlop.setMaximum(20)
        self.secondRoundAdjustmentPreFlop.setSingleStep(1)
        self.secondRoundAdjustmentPreFlop.setPageStep(5)
        self.secondRoundAdjustmentPreFlop.setProperty("value", 20)
        self.secondRoundAdjustmentPreFlop.setOrientation(QtCore.Qt.Horizontal)
        self.secondRoundAdjustmentPreFlop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.secondRoundAdjustmentPreFlop.setObjectName("secondRoundAdjustmentPreFlop")
        self.verticalLayout_28.addWidget(self.secondRoundAdjustmentPreFlop)
        self.gridLayout_2.addLayout(self.verticalLayout_28, 10, 0, 1, 1)
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.gridLayout_2.addWidget(self.lcdNumber_16, 10, 1, 1, 1)
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.gridLayout_2.addWidget(self.lcdNumber_18, 9, 3, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_2.addWidget(self.lcdNumber_9, 8, 1, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_35 = QtWidgets.QLabel(self.PreFlop)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_30.addWidget(self.label_35)
        self.potAdjustmentPreFlop = QtWidgets.QSlider(self.PreFlop)
        self.potAdjustmentPreFlop.setMouseTracking(False)
        self.potAdjustmentPreFlop.setMinimum(0)
        self.potAdjustmentPreFlop.setMaximum(5)
        self.potAdjustmentPreFlop.setPageStep(1)
        self.potAdjustmentPreFlop.setOrientation(QtCore.Qt.Horizontal)
        self.potAdjustmentPreFlop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.potAdjustmentPreFlop.setObjectName("potAdjustmentPreFlop")
        self.verticalLayout_30.addWidget(self.potAdjustmentPreFlop)
        self.gridLayout_2.addLayout(self.verticalLayout_30, 8, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.PreFlop)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.CoveredPlayersCallLikelihoodPreFlop = QtWidgets.QSlider(self.PreFlop)
        self.CoveredPlayersCallLikelihoodPreFlop.setMouseTracking(False)
        self.CoveredPlayersCallLikelihoodPreFlop.setMinimum(1)
        self.CoveredPlayersCallLikelihoodPreFlop.setMaximum(100)
        self.CoveredPlayersCallLikelihoodPreFlop.setPageStep(5)
        self.CoveredPlayersCallLikelihoodPreFlop.setProperty("value", 3)
        self.CoveredPlayersCallLikelihoodPreFlop.setOrientation(QtCore.Qt.Horizontal)
        self.CoveredPlayersCallLikelihoodPreFlop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.CoveredPlayersCallLikelihoodPreFlop.setObjectName("CoveredPlayersCallLikelihoodPreFlop")
        self.verticalLayout_12.addWidget(self.CoveredPlayersCallLikelihoodPreFlop)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 8, 0, 1, 1)
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.gridLayout_2.addWidget(self.lcdNumber_17, 8, 3, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.PreFlop)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.slider_FlopBluffMinEquity = QtWidgets.QSlider(self.PreFlop)
        self.slider_FlopBluffMinEquity.setMouseTracking(False)
        self.slider_FlopBluffMinEquity.setMinimum(1)
        self.slider_FlopBluffMinEquity.setMaximum(100)
        self.slider_FlopBluffMinEquity.setSingleStep(1)
        self.slider_FlopBluffMinEquity.setPageStep(5)
        self.slider_FlopBluffMinEquity.setProperty("value", 50)
        self.slider_FlopBluffMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.slider_FlopBluffMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_FlopBluffMinEquity.setObjectName("slider_FlopBluffMinEquity")
        self.verticalLayout_13.addWidget(self.slider_FlopBluffMinEquity)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 9, 0, 1, 1)
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.gridLayout_2.addWidget(self.lcdNumber_15, 9, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.PreFlop)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 2, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_237 = QtWidgets.QLabel(self.PreFlop)
        self.label_237.setObjectName("label_237")
        self.verticalLayout_8.addWidget(self.label_237)
        self.PreFlopMinCallEquity = QtWidgets.QSlider(self.PreFlop)
        self.PreFlopMinCallEquity.setMouseTracking(False)
        self.PreFlopMinCallEquity.setMinimum(1)
        self.PreFlopMinCallEquity.setMaximum(100)
        self.PreFlopMinCallEquity.setSingleStep(1)
        self.PreFlopMinCallEquity.setPageStep(5)
        self.PreFlopMinCallEquity.setProperty("value", 50)
        self.PreFlopMinCallEquity.setOrientation(QtCore.Qt.Horizontal)
        self.PreFlopMinCallEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.PreFlopMinCallEquity.setObjectName("PreFlopMinCallEquity")
        self.verticalLayout_8.addWidget(self.PreFlopMinCallEquity)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.verticalLayout_381 = QtWidgets.QVBoxLayout()
        self.verticalLayout_381.setObjectName("verticalLayout_381")
        self.label_394 = QtWidgets.QLabel(self.PreFlop)
        self.label_394.setObjectName("label_394")
        self.verticalLayout_381.addWidget(self.label_394)
        self.PreFlopMaxBetEquity = QtWidgets.QSlider(self.PreFlop)
        self.PreFlopMaxBetEquity.setMouseTracking(False)
        self.PreFlopMaxBetEquity.setMinimum(2)
        self.PreFlopMaxBetEquity.setMaximum(100)
        self.PreFlopMaxBetEquity.setSingleStep(5)
        self.PreFlopMaxBetEquity.setPageStep(10)
        self.PreFlopMaxBetEquity.setOrientation(QtCore.Qt.Horizontal)
        self.PreFlopMaxBetEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.PreFlopMaxBetEquity.setTickInterval(5)
        self.PreFlopMaxBetEquity.setObjectName("PreFlopMaxBetEquity")
        self.verticalLayout_381.addWidget(self.PreFlopMaxBetEquity)
        self.gridLayout_2.addLayout(self.verticalLayout_381, 7, 0, 1, 1)
        self.lcdNumber_63 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_63.setObjectName("lcdNumber_63")
        self.gridLayout_2.addWidget(self.lcdNumber_63, 7, 1, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout_2.addWidget(self.lcdNumber_4, 6, 1, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_2.addWidget(self.lcdNumber_2, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.PreFlop)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.PreFlop)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.PreFlopCallPower = QtWidgets.QSlider(self.PreFlop)
        self.PreFlopCallPower.setMouseTracking(False)
        self.PreFlopCallPower.setMinimum(2)
        self.PreFlopCallPower.setMaximum(30)
        self.PreFlopCallPower.setSingleStep(5)
        self.PreFlopCallPower.setPageStep(10)
        self.PreFlopCallPower.setOrientation(QtCore.Qt.Horizontal)
        self.PreFlopCallPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.PreFlopCallPower.setTickInterval(5)
        self.PreFlopCallPower.setObjectName("PreFlopCallPower")
        self.verticalLayout_9.addWidget(self.PreFlopCallPower)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 2, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 5, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.PreFlop)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.PreFlopMinBetEquity = QtWidgets.QSlider(self.PreFlop)
        self.PreFlopMinBetEquity.setMouseTracking(False)
        self.PreFlopMinBetEquity.setMinimum(1)
        self.PreFlopMinBetEquity.setMaximum(100)
        self.PreFlopMinBetEquity.setSingleStep(1)
        self.PreFlopMinBetEquity.setPageStep(5)
        self.PreFlopMinBetEquity.setProperty("value", 50)
        self.PreFlopMinBetEquity.setOrientation(QtCore.Qt.Horizontal)
        self.PreFlopMinBetEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.PreFlopMinBetEquity.setObjectName("PreFlopMinBetEquity")
        self.verticalLayout_10.addWidget(self.PreFlopMinBetEquity)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 5, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.PreFlop)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.PreFlopBetPower = QtWidgets.QSlider(self.PreFlop)
        self.PreFlopBetPower.setMouseTracking(False)
        self.PreFlopBetPower.setMinimum(1)
        self.PreFlopBetPower.setMaximum(30)
        self.PreFlopBetPower.setSingleStep(5)
        self.PreFlopBetPower.setPageStep(10)
        self.PreFlopBetPower.setOrientation(QtCore.Qt.Horizontal)
        self.PreFlopBetPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.PreFlopBetPower.setTickInterval(5)
        self.PreFlopBetPower.setObjectName("PreFlopBetPower")
        self.verticalLayout_11.addWidget(self.PreFlopBetPower)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 6, 0, 1, 1)
        self.verticalLayout_434 = QtWidgets.QVBoxLayout()
        self.verticalLayout_434.setObjectName("verticalLayout_434")
        self.label_451 = QtWidgets.QLabel(self.PreFlop)
        self.label_451.setObjectName("label_451")
        self.verticalLayout_434.addWidget(self.label_451)
        self.secondRoundAdjustmentPowerIncrease = QtWidgets.QSlider(self.PreFlop)
        self.secondRoundAdjustmentPowerIncrease.setMouseTracking(False)
        self.secondRoundAdjustmentPowerIncrease.setMinimum(0)
        self.secondRoundAdjustmentPowerIncrease.setMaximum(10)
        self.secondRoundAdjustmentPowerIncrease.setPageStep(1)
        self.secondRoundAdjustmentPowerIncrease.setOrientation(QtCore.Qt.Horizontal)
        self.secondRoundAdjustmentPowerIncrease.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.secondRoundAdjustmentPowerIncrease.setObjectName("secondRoundAdjustmentPowerIncrease")
        self.verticalLayout_434.addWidget(self.secondRoundAdjustmentPowerIncrease)
        self.gridLayout_2.addLayout(self.verticalLayout_434, 10, 2, 1, 1)
        self.lcdNumber_111 = QtWidgets.QLCDNumber(self.PreFlop)
        self.lcdNumber_111.setObjectName("lcdNumber_111")
        self.gridLayout_2.addWidget(self.lcdNumber_111, 10, 3, 1, 1)
        self.verticalLayout_preflop = QtWidgets.QVBoxLayout()
        self.verticalLayout_preflop.setObjectName("verticalLayout_preflop")
        self.widget_4 = QtWidgets.QWidget(self.PreFlop)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_preflop.addWidget(self.widget_4)
        self.gridLayout_2.addLayout(self.verticalLayout_preflop, 1, 2, 7, 2)
        self.pushButton_update1 = QtWidgets.QPushButton(self.PreFlop)
        self.pushButton_update1.setObjectName("pushButton_update1")
        self.gridLayout_2.addWidget(self.pushButton_update1, 0, 2, 1, 1)
        self.tabWidget.addTab(self.PreFlop, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 681, 531))
        self.tableView.setObjectName("tableView")
        self.preflop_override = QtWidgets.QCheckBox(self.tab_3)
        self.preflop_override.setGeometry(QtCore.QRect(10, 20, 181, 17))
        self.preflop_override.setObjectName("preflop_override")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_433 = QtWidgets.QVBoxLayout()
        self.verticalLayout_433.setObjectName("verticalLayout_433")
        self.label_450 = QtWidgets.QLabel(self.tab_2)
        self.label_450.setObjectName("label_450")
        self.verticalLayout_433.addWidget(self.label_450)
        self.FlopCheckDeceptionMinEquity = QtWidgets.QSlider(self.tab_2)
        self.FlopCheckDeceptionMinEquity.setMouseTracking(False)
        self.FlopCheckDeceptionMinEquity.setMinimum(50)
        self.FlopCheckDeceptionMinEquity.setMaximum(99)
        self.FlopCheckDeceptionMinEquity.setPageStep(1)
        self.FlopCheckDeceptionMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.FlopCheckDeceptionMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopCheckDeceptionMinEquity.setObjectName("FlopCheckDeceptionMinEquity")
        self.verticalLayout_433.addWidget(self.FlopCheckDeceptionMinEquity)
        self.gridLayout_4.addLayout(self.verticalLayout_433, 11, 2, 1, 1)
        self.verticalLayout_181 = QtWidgets.QVBoxLayout()
        self.verticalLayout_181.setObjectName("verticalLayout_181")
        self.label_177 = QtWidgets.QLabel(self.tab_2)
        self.label_177.setObjectName("label_177")
        self.verticalLayout_181.addWidget(self.label_177)
        self.secondRoundAdjustment = QtWidgets.QSlider(self.tab_2)
        self.secondRoundAdjustment.setMouseTracking(False)
        self.secondRoundAdjustment.setMinimum(0)
        self.secondRoundAdjustment.setMaximum(20)
        self.secondRoundAdjustment.setSingleStep(1)
        self.secondRoundAdjustment.setPageStep(5)
        self.secondRoundAdjustment.setProperty("value", 20)
        self.secondRoundAdjustment.setOrientation(QtCore.Qt.Horizontal)
        self.secondRoundAdjustment.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.secondRoundAdjustment.setObjectName("secondRoundAdjustment")
        self.verticalLayout_181.addWidget(self.secondRoundAdjustment)
        self.gridLayout_4.addLayout(self.verticalLayout_181, 11, 0, 1, 1)
        self.lcdNumber_35 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_35.setObjectName("lcdNumber_35")
        self.gridLayout_4.addWidget(self.lcdNumber_35, 11, 1, 1, 1)
        self.label_175 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.gridLayout_4.addWidget(self.label_175, 0, 0, 2, 1)
        self.verticalLayout_flop = QtWidgets.QVBoxLayout()
        self.verticalLayout_flop.setObjectName("verticalLayout_flop")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_flop.addWidget(self.widget_3)
        self.gridLayout_4.addLayout(self.verticalLayout_flop, 1, 2, 6, 2)
        self.verticalLayout_183 = QtWidgets.QVBoxLayout()
        self.verticalLayout_183.setObjectName("verticalLayout_183")
        self.label_179 = QtWidgets.QLabel(self.tab_2)
        self.label_179.setObjectName("label_179")
        self.verticalLayout_183.addWidget(self.label_179)
        self.FlopMinCallEquity = QtWidgets.QSlider(self.tab_2)
        self.FlopMinCallEquity.setMouseTracking(False)
        self.FlopMinCallEquity.setMinimum(1)
        self.FlopMinCallEquity.setMaximum(100)
        self.FlopMinCallEquity.setSingleStep(1)
        self.FlopMinCallEquity.setPageStep(5)
        self.FlopMinCallEquity.setProperty("value", 50)
        self.FlopMinCallEquity.setOrientation(QtCore.Qt.Horizontal)
        self.FlopMinCallEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopMinCallEquity.setObjectName("FlopMinCallEquity")
        self.verticalLayout_183.addWidget(self.FlopMinCallEquity)
        self.gridLayout_4.addLayout(self.verticalLayout_183, 2, 0, 1, 1)
        self.lcdNumber_34 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_34.setObjectName("lcdNumber_34")
        self.gridLayout_4.addWidget(self.lcdNumber_34, 2, 1, 1, 1)
        self.verticalLayout_186 = QtWidgets.QVBoxLayout()
        self.verticalLayout_186.setObjectName("verticalLayout_186")
        self.label_182 = QtWidgets.QLabel(self.tab_2)
        self.label_182.setObjectName("label_182")
        self.verticalLayout_186.addWidget(self.label_182)
        self.FlopMinBetEquity = QtWidgets.QSlider(self.tab_2)
        self.FlopMinBetEquity.setMouseTracking(False)
        self.FlopMinBetEquity.setMinimum(1)
        self.FlopMinBetEquity.setMaximum(100)
        self.FlopMinBetEquity.setSingleStep(1)
        self.FlopMinBetEquity.setPageStep(5)
        self.FlopMinBetEquity.setProperty("value", 50)
        self.FlopMinBetEquity.setOrientation(QtCore.Qt.Horizontal)
        self.FlopMinBetEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopMinBetEquity.setObjectName("FlopMinBetEquity")
        self.verticalLayout_186.addWidget(self.FlopMinBetEquity)
        self.gridLayout_4.addLayout(self.verticalLayout_186, 5, 0, 1, 1)
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.gridLayout_4.addWidget(self.lcdNumber_29, 3, 1, 1, 1)
        self.label_184 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_184.setFont(font)
        self.label_184.setObjectName("label_184")
        self.gridLayout_4.addWidget(self.label_184, 4, 0, 1, 1)
        self.verticalLayout_184 = QtWidgets.QVBoxLayout()
        self.verticalLayout_184.setObjectName("verticalLayout_184")
        self.label_180 = QtWidgets.QLabel(self.tab_2)
        self.label_180.setObjectName("label_180")
        self.verticalLayout_184.addWidget(self.label_180)
        self.FlopCallPower = QtWidgets.QSlider(self.tab_2)
        self.FlopCallPower.setMouseTracking(False)
        self.FlopCallPower.setMinimum(2)
        self.FlopCallPower.setMaximum(30)
        self.FlopCallPower.setSingleStep(5)
        self.FlopCallPower.setPageStep(10)
        self.FlopCallPower.setOrientation(QtCore.Qt.Horizontal)
        self.FlopCallPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopCallPower.setTickInterval(5)
        self.FlopCallPower.setObjectName("FlopCallPower")
        self.verticalLayout_184.addWidget(self.FlopCallPower)
        self.gridLayout_4.addLayout(self.verticalLayout_184, 3, 0, 1, 1)
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.gridLayout_4.addWidget(self.lcdNumber_28, 6, 1, 1, 1)
        self.verticalLayout_179 = QtWidgets.QVBoxLayout()
        self.verticalLayout_179.setObjectName("verticalLayout_179")
        self.label_176 = QtWidgets.QLabel(self.tab_2)
        self.label_176.setObjectName("label_176")
        self.verticalLayout_179.addWidget(self.label_176)
        self.FlopBetPower = QtWidgets.QSlider(self.tab_2)
        self.FlopBetPower.setMouseTracking(False)
        self.FlopBetPower.setMinimum(2)
        self.FlopBetPower.setMaximum(30)
        self.FlopBetPower.setSingleStep(5)
        self.FlopBetPower.setPageStep(10)
        self.FlopBetPower.setOrientation(QtCore.Qt.Horizontal)
        self.FlopBetPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopBetPower.setTickInterval(5)
        self.FlopBetPower.setObjectName("FlopBetPower")
        self.verticalLayout_179.addWidget(self.FlopBetPower)
        self.gridLayout_4.addLayout(self.verticalLayout_179, 6, 0, 1, 1)
        self.lcdNumber_36 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_36.setObjectName("lcdNumber_36")
        self.gridLayout_4.addWidget(self.lcdNumber_36, 5, 1, 1, 1)
        self.verticalLayout_182 = QtWidgets.QVBoxLayout()
        self.verticalLayout_182.setObjectName("verticalLayout_182")
        self.label_178 = QtWidgets.QLabel(self.tab_2)
        self.label_178.setObjectName("label_178")
        self.verticalLayout_182.addWidget(self.label_178)
        self.CoveredPlayersCallLikelihoodFlop = QtWidgets.QSlider(self.tab_2)
        self.CoveredPlayersCallLikelihoodFlop.setMouseTracking(False)
        self.CoveredPlayersCallLikelihoodFlop.setMinimum(1)
        self.CoveredPlayersCallLikelihoodFlop.setMaximum(100)
        self.CoveredPlayersCallLikelihoodFlop.setPageStep(5)
        self.CoveredPlayersCallLikelihoodFlop.setProperty("value", 3)
        self.CoveredPlayersCallLikelihoodFlop.setOrientation(QtCore.Qt.Horizontal)
        self.CoveredPlayersCallLikelihoodFlop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.CoveredPlayersCallLikelihoodFlop.setObjectName("CoveredPlayersCallLikelihoodFlop")
        self.verticalLayout_182.addWidget(self.CoveredPlayersCallLikelihoodFlop)
        self.gridLayout_4.addLayout(self.verticalLayout_182, 8, 0, 1, 1)
        self.verticalLayout_188 = QtWidgets.QVBoxLayout()
        self.verticalLayout_188.setObjectName("verticalLayout_188")
        self.label_185 = QtWidgets.QLabel(self.tab_2)
        self.label_185.setObjectName("label_185")
        self.verticalLayout_188.addWidget(self.label_185)
        self.potAdjustment = QtWidgets.QSlider(self.tab_2)
        self.potAdjustment.setMouseTracking(False)
        self.potAdjustment.setMinimum(0)
        self.potAdjustment.setMaximum(5)
        self.potAdjustment.setPageStep(1)
        self.potAdjustment.setOrientation(QtCore.Qt.Horizontal)
        self.potAdjustment.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.potAdjustment.setObjectName("potAdjustment")
        self.verticalLayout_188.addWidget(self.potAdjustment)
        self.gridLayout_4.addLayout(self.verticalLayout_188, 8, 2, 1, 1)
        self.lcdNumber_32 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.gridLayout_4.addWidget(self.lcdNumber_32, 8, 3, 1, 1)
        self.lcdNumber_30 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.gridLayout_4.addWidget(self.lcdNumber_30, 8, 1, 1, 1)
        self.lcdNumber_33 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_33.setObjectName("lcdNumber_33")
        self.gridLayout_4.addWidget(self.lcdNumber_33, 9, 1, 1, 1)
        self.verticalLayout_187 = QtWidgets.QVBoxLayout()
        self.verticalLayout_187.setObjectName("verticalLayout_187")
        self.label_183 = QtWidgets.QLabel(self.tab_2)
        self.label_183.setObjectName("label_183")
        self.verticalLayout_187.addWidget(self.label_183)
        self.FlopBluffMinEquity = QtWidgets.QSlider(self.tab_2)
        self.FlopBluffMinEquity.setMouseTracking(False)
        self.FlopBluffMinEquity.setMinimum(1)
        self.FlopBluffMinEquity.setMaximum(100)
        self.FlopBluffMinEquity.setSingleStep(1)
        self.FlopBluffMinEquity.setPageStep(5)
        self.FlopBluffMinEquity.setProperty("value", 50)
        self.FlopBluffMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.FlopBluffMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.FlopBluffMinEquity.setObjectName("FlopBluffMinEquity")
        self.verticalLayout_187.addWidget(self.FlopBluffMinEquity)
        self.gridLayout_4.addLayout(self.verticalLayout_187, 9, 0, 1, 1)
        self.verticalLayout_185 = QtWidgets.QVBoxLayout()
        self.verticalLayout_185.setObjectName("verticalLayout_185")
        self.label_181 = QtWidgets.QLabel(self.tab_2)
        self.label_181.setObjectName("label_181")
        self.verticalLayout_185.addWidget(self.label_181)
        self.maxPotAdjustment = QtWidgets.QSlider(self.tab_2)
        self.maxPotAdjustment.setMouseTracking(False)
        self.maxPotAdjustment.setMinimum(1)
        self.maxPotAdjustment.setMaximum(10)
        self.maxPotAdjustment.setPageStep(1)
        self.maxPotAdjustment.setOrientation(QtCore.Qt.Horizontal)
        self.maxPotAdjustment.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.maxPotAdjustment.setObjectName("maxPotAdjustment")
        self.verticalLayout_185.addWidget(self.maxPotAdjustment)
        self.gridLayout_4.addLayout(self.verticalLayout_185, 9, 2, 1, 1)
        self.lcdNumber_31 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.gridLayout_4.addWidget(self.lcdNumber_31, 9, 3, 1, 1)
        self.pushButton_update2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update2.setObjectName("pushButton_update2")
        self.gridLayout_4.addWidget(self.pushButton_update2, 0, 2, 1, 1)
        self.lcdNumber_110 = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber_110.setObjectName("lcdNumber_110")
        self.gridLayout_4.addWidget(self.lcdNumber_110, 11, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.WorstGames = QtWidgets.QWidget()
        self.WorstGames.setObjectName("WorstGames")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.WorstGames)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_turn = QtWidgets.QVBoxLayout()
        self.verticalLayout_turn.setObjectName("verticalLayout_turn")
        self.widget_2 = QtWidgets.QWidget(self.WorstGames)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_turn.addWidget(self.widget_2)
        self.gridLayout_5.addLayout(self.verticalLayout_turn, 1, 2, 6, 2)
        self.label_9 = QtWidgets.QLabel(self.WorstGames)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 2, 1)
        self.lcdNumber_43 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_43.setObjectName("lcdNumber_43")
        self.gridLayout_5.addWidget(self.lcdNumber_43, 2, 1, 1, 1)
        self.verticalLayout_112 = QtWidgets.QVBoxLayout()
        self.verticalLayout_112.setObjectName("verticalLayout_112")
        self.label_109 = QtWidgets.QLabel(self.WorstGames)
        self.label_109.setObjectName("label_109")
        self.verticalLayout_112.addWidget(self.label_109)
        self.TurnMinCallEquity = QtWidgets.QSlider(self.WorstGames)
        self.TurnMinCallEquity.setMouseTracking(False)
        self.TurnMinCallEquity.setMinimum(1)
        self.TurnMinCallEquity.setMaximum(100)
        self.TurnMinCallEquity.setSingleStep(1)
        self.TurnMinCallEquity.setPageStep(5)
        self.TurnMinCallEquity.setProperty("value", 50)
        self.TurnMinCallEquity.setOrientation(QtCore.Qt.Horizontal)
        self.TurnMinCallEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TurnMinCallEquity.setObjectName("TurnMinCallEquity")
        self.verticalLayout_112.addWidget(self.TurnMinCallEquity)
        self.gridLayout_5.addLayout(self.verticalLayout_112, 2, 0, 1, 1)
        self.verticalLayout_114 = QtWidgets.QVBoxLayout()
        self.verticalLayout_114.setObjectName("verticalLayout_114")
        self.label_111 = QtWidgets.QLabel(self.WorstGames)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_114.addWidget(self.label_111)
        self.TurnCallPower = QtWidgets.QSlider(self.WorstGames)
        self.TurnCallPower.setMouseTracking(False)
        self.TurnCallPower.setMinimum(2)
        self.TurnCallPower.setMaximum(30)
        self.TurnCallPower.setSingleStep(5)
        self.TurnCallPower.setPageStep(10)
        self.TurnCallPower.setOrientation(QtCore.Qt.Horizontal)
        self.TurnCallPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TurnCallPower.setTickInterval(5)
        self.TurnCallPower.setObjectName("TurnCallPower")
        self.verticalLayout_114.addWidget(self.TurnCallPower)
        self.gridLayout_5.addLayout(self.verticalLayout_114, 3, 0, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.WorstGames)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_235.setFont(font)
        self.label_235.setObjectName("label_235")
        self.gridLayout_5.addWidget(self.label_235, 4, 0, 1, 1)
        self.lcdNumber_38 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_38.setObjectName("lcdNumber_38")
        self.gridLayout_5.addWidget(self.lcdNumber_38, 3, 1, 1, 1)
        self.verticalLayout_117 = QtWidgets.QVBoxLayout()
        self.verticalLayout_117.setObjectName("verticalLayout_117")
        self.label_114 = QtWidgets.QLabel(self.WorstGames)
        self.label_114.setObjectName("label_114")
        self.verticalLayout_117.addWidget(self.label_114)
        self.TurnMinBetEquity = QtWidgets.QSlider(self.WorstGames)
        self.TurnMinBetEquity.setMouseTracking(False)
        self.TurnMinBetEquity.setMinimum(1)
        self.TurnMinBetEquity.setMaximum(100)
        self.TurnMinBetEquity.setSingleStep(1)
        self.TurnMinBetEquity.setPageStep(5)
        self.TurnMinBetEquity.setProperty("value", 50)
        self.TurnMinBetEquity.setOrientation(QtCore.Qt.Horizontal)
        self.TurnMinBetEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TurnMinBetEquity.setObjectName("TurnMinBetEquity")
        self.verticalLayout_117.addWidget(self.TurnMinBetEquity)
        self.gridLayout_5.addLayout(self.verticalLayout_117, 5, 0, 1, 1)
        self.lcdNumber_45 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_45.setObjectName("lcdNumber_45")
        self.gridLayout_5.addWidget(self.lcdNumber_45, 5, 1, 1, 1)
        self.lcdNumber_37 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_37.setObjectName("lcdNumber_37")
        self.gridLayout_5.addWidget(self.lcdNumber_37, 6, 1, 1, 1)
        self.verticalLayout_109 = QtWidgets.QVBoxLayout()
        self.verticalLayout_109.setObjectName("verticalLayout_109")
        self.label_107 = QtWidgets.QLabel(self.WorstGames)
        self.label_107.setObjectName("label_107")
        self.verticalLayout_109.addWidget(self.label_107)
        self.TurnBetPower = QtWidgets.QSlider(self.WorstGames)
        self.TurnBetPower.setMouseTracking(False)
        self.TurnBetPower.setMinimum(2)
        self.TurnBetPower.setMaximum(30)
        self.TurnBetPower.setSingleStep(5)
        self.TurnBetPower.setPageStep(10)
        self.TurnBetPower.setOrientation(QtCore.Qt.Horizontal)
        self.TurnBetPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TurnBetPower.setObjectName("TurnBetPower")
        self.verticalLayout_109.addWidget(self.TurnBetPower)
        self.gridLayout_5.addLayout(self.verticalLayout_109, 6, 0, 1, 1)
        self.verticalLayout_118 = QtWidgets.QVBoxLayout()
        self.verticalLayout_118.setObjectName("verticalLayout_118")
        self.label_115 = QtWidgets.QLabel(self.WorstGames)
        self.label_115.setObjectName("label_115")
        self.verticalLayout_118.addWidget(self.label_115)
        self.slider_small_blind_51 = QtWidgets.QSlider(self.WorstGames)
        self.slider_small_blind_51.setEnabled(False)
        self.slider_small_blind_51.setMouseTracking(False)
        self.slider_small_blind_51.setMinimum(0)
        self.slider_small_blind_51.setMaximum(5)
        self.slider_small_blind_51.setPageStep(1)
        self.slider_small_blind_51.setOrientation(QtCore.Qt.Horizontal)
        self.slider_small_blind_51.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_small_blind_51.setObjectName("slider_small_blind_51")
        self.verticalLayout_118.addWidget(self.slider_small_blind_51)
        self.gridLayout_5.addLayout(self.verticalLayout_118, 7, 2, 1, 1)
        self.verticalLayout_116 = QtWidgets.QVBoxLayout()
        self.verticalLayout_116.setObjectName("verticalLayout_116")
        self.label_113 = QtWidgets.QLabel(self.WorstGames)
        self.label_113.setObjectName("label_113")
        self.verticalLayout_116.addWidget(self.label_113)
        self.TurnBluffMinEquity = QtWidgets.QSlider(self.WorstGames)
        self.TurnBluffMinEquity.setMouseTracking(False)
        self.TurnBluffMinEquity.setMinimum(1)
        self.TurnBluffMinEquity.setMaximum(100)
        self.TurnBluffMinEquity.setSingleStep(1)
        self.TurnBluffMinEquity.setPageStep(5)
        self.TurnBluffMinEquity.setProperty("value", 50)
        self.TurnBluffMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.TurnBluffMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.TurnBluffMinEquity.setObjectName("TurnBluffMinEquity")
        self.verticalLayout_116.addWidget(self.TurnBluffMinEquity)
        self.gridLayout_5.addLayout(self.verticalLayout_116, 8, 0, 1, 1)
        self.lcdNumber_41 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_41.setObjectName("lcdNumber_41")
        self.gridLayout_5.addWidget(self.lcdNumber_41, 7, 3, 1, 1)
        self.lcdNumber_42 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_42.setObjectName("lcdNumber_42")
        self.gridLayout_5.addWidget(self.lcdNumber_42, 8, 1, 1, 1)
        self.verticalLayout_115 = QtWidgets.QVBoxLayout()
        self.verticalLayout_115.setObjectName("verticalLayout_115")
        self.label_112 = QtWidgets.QLabel(self.WorstGames)
        self.label_112.setObjectName("label_112")
        self.verticalLayout_115.addWidget(self.label_112)
        self.slider_small_blind_50 = QtWidgets.QSlider(self.WorstGames)
        self.slider_small_blind_50.setEnabled(False)
        self.slider_small_blind_50.setMouseTracking(False)
        self.slider_small_blind_50.setMinimum(1)
        self.slider_small_blind_50.setMaximum(10)
        self.slider_small_blind_50.setPageStep(1)
        self.slider_small_blind_50.setOrientation(QtCore.Qt.Horizontal)
        self.slider_small_blind_50.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_small_blind_50.setObjectName("slider_small_blind_50")
        self.verticalLayout_115.addWidget(self.slider_small_blind_50)
        self.gridLayout_5.addLayout(self.verticalLayout_115, 8, 2, 1, 1)
        self.lcdNumber_40 = QtWidgets.QLCDNumber(self.WorstGames)
        self.lcdNumber_40.setObjectName("lcdNumber_40")
        self.gridLayout_5.addWidget(self.lcdNumber_40, 8, 3, 1, 1)
        self.pushButton_update3 = QtWidgets.QPushButton(self.WorstGames)
        self.pushButton_update3.setObjectName("pushButton_update3")
        self.gridLayout_5.addWidget(self.pushButton_update3, 0, 2, 1, 1)
        self.tabWidget.addTab(self.WorstGames, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 2, 1)
        self.verticalLayout_river = QtWidgets.QVBoxLayout()
        self.verticalLayout_river.setObjectName("verticalLayout_river")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_river.addWidget(self.widget)
        self.gridLayout_6.addLayout(self.verticalLayout_river, 1, 2, 6, 2)
        self.verticalLayout_132 = QtWidgets.QVBoxLayout()
        self.verticalLayout_132.setObjectName("verticalLayout_132")
        self.label_127 = QtWidgets.QLabel(self.tab)
        self.label_127.setObjectName("label_127")
        self.verticalLayout_132.addWidget(self.label_127)
        self.RiverMinCallEquity = QtWidgets.QSlider(self.tab)
        self.RiverMinCallEquity.setMouseTracking(False)
        self.RiverMinCallEquity.setMinimum(1)
        self.RiverMinCallEquity.setMaximum(100)
        self.RiverMinCallEquity.setSingleStep(1)
        self.RiverMinCallEquity.setPageStep(5)
        self.RiverMinCallEquity.setProperty("value", 50)
        self.RiverMinCallEquity.setOrientation(QtCore.Qt.Horizontal)
        self.RiverMinCallEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RiverMinCallEquity.setObjectName("RiverMinCallEquity")
        self.verticalLayout_132.addWidget(self.RiverMinCallEquity)
        self.gridLayout_6.addLayout(self.verticalLayout_132, 2, 0, 1, 1)
        self.lcdNumber_52 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_52.setObjectName("lcdNumber_52")
        self.gridLayout_6.addWidget(self.lcdNumber_52, 2, 1, 1, 1)
        self.verticalLayout_134 = QtWidgets.QVBoxLayout()
        self.verticalLayout_134.setObjectName("verticalLayout_134")
        self.label_129 = QtWidgets.QLabel(self.tab)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_134.addWidget(self.label_129)
        self.RiverCallPower = QtWidgets.QSlider(self.tab)
        self.RiverCallPower.setMouseTracking(False)
        self.RiverCallPower.setMinimum(2)
        self.RiverCallPower.setMaximum(30)
        self.RiverCallPower.setSingleStep(5)
        self.RiverCallPower.setPageStep(10)
        self.RiverCallPower.setOrientation(QtCore.Qt.Horizontal)
        self.RiverCallPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RiverCallPower.setTickInterval(5)
        self.RiverCallPower.setObjectName("RiverCallPower")
        self.verticalLayout_134.addWidget(self.RiverCallPower)
        self.gridLayout_6.addLayout(self.verticalLayout_134, 3, 0, 1, 1)
        self.lcdNumber_47 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_47.setObjectName("lcdNumber_47")
        self.gridLayout_6.addWidget(self.lcdNumber_47, 3, 1, 1, 1)
        self.label_236 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_236.setFont(font)
        self.label_236.setObjectName("label_236")
        self.gridLayout_6.addWidget(self.label_236, 4, 0, 1, 1)
        self.verticalLayout_137 = QtWidgets.QVBoxLayout()
        self.verticalLayout_137.setObjectName("verticalLayout_137")
        self.label_132 = QtWidgets.QLabel(self.tab)
        self.label_132.setObjectName("label_132")
        self.verticalLayout_137.addWidget(self.label_132)
        self.RiverMinBetEquity = QtWidgets.QSlider(self.tab)
        self.RiverMinBetEquity.setMouseTracking(False)
        self.RiverMinBetEquity.setMinimum(1)
        self.RiverMinBetEquity.setMaximum(100)
        self.RiverMinBetEquity.setSingleStep(1)
        self.RiverMinBetEquity.setPageStep(5)
        self.RiverMinBetEquity.setProperty("value", 50)
        self.RiverMinBetEquity.setOrientation(QtCore.Qt.Horizontal)
        self.RiverMinBetEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RiverMinBetEquity.setObjectName("RiverMinBetEquity")
        self.verticalLayout_137.addWidget(self.RiverMinBetEquity)
        self.gridLayout_6.addLayout(self.verticalLayout_137, 5, 0, 1, 1)
        self.lcdNumber_54 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_54.setObjectName("lcdNumber_54")
        self.gridLayout_6.addWidget(self.lcdNumber_54, 5, 1, 1, 1)
        self.verticalLayout_129 = QtWidgets.QVBoxLayout()
        self.verticalLayout_129.setObjectName("verticalLayout_129")
        self.label_125 = QtWidgets.QLabel(self.tab)
        self.label_125.setObjectName("label_125")
        self.verticalLayout_129.addWidget(self.label_125)
        self.RiverBetPower = QtWidgets.QSlider(self.tab)
        self.RiverBetPower.setMouseTracking(False)
        self.RiverBetPower.setMinimum(2)
        self.RiverBetPower.setMaximum(30)
        self.RiverBetPower.setSingleStep(5)
        self.RiverBetPower.setPageStep(10)
        self.RiverBetPower.setOrientation(QtCore.Qt.Horizontal)
        self.RiverBetPower.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RiverBetPower.setTickInterval(5)
        self.RiverBetPower.setObjectName("RiverBetPower")
        self.verticalLayout_129.addWidget(self.RiverBetPower)
        self.gridLayout_6.addLayout(self.verticalLayout_129, 6, 0, 1, 1)
        self.lcdNumber_46 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_46.setObjectName("lcdNumber_46")
        self.gridLayout_6.addWidget(self.lcdNumber_46, 6, 1, 1, 1)
        self.verticalLayout_133 = QtWidgets.QVBoxLayout()
        self.verticalLayout_133.setObjectName("verticalLayout_133")
        self.label_128 = QtWidgets.QLabel(self.tab)
        self.label_128.setObjectName("label_128")
        self.verticalLayout_133.addWidget(self.label_128)
        self.secondRiverBetPotMinEquity = QtWidgets.QSlider(self.tab)
        self.secondRiverBetPotMinEquity.setMouseTracking(False)
        self.secondRiverBetPotMinEquity.setMinimum(1)
        self.secondRiverBetPotMinEquity.setMaximum(100)
        self.secondRiverBetPotMinEquity.setPageStep(5)
        self.secondRiverBetPotMinEquity.setProperty("value", 3)
        self.secondRiverBetPotMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.secondRiverBetPotMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.secondRiverBetPotMinEquity.setObjectName("secondRiverBetPotMinEquity")
        self.verticalLayout_133.addWidget(self.secondRiverBetPotMinEquity)
        self.gridLayout_6.addLayout(self.verticalLayout_133, 7, 0, 1, 1)
        self.lcdNumber_48 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_48.setObjectName("lcdNumber_48")
        self.gridLayout_6.addWidget(self.lcdNumber_48, 7, 1, 1, 1)
        self.verticalLayout_138 = QtWidgets.QVBoxLayout()
        self.verticalLayout_138.setObjectName("verticalLayout_138")
        self.label_133 = QtWidgets.QLabel(self.tab)
        self.label_133.setObjectName("label_133")
        self.verticalLayout_138.addWidget(self.label_133)
        self.slider_small_blind_57 = QtWidgets.QSlider(self.tab)
        self.slider_small_blind_57.setEnabled(False)
        self.slider_small_blind_57.setMouseTracking(False)
        self.slider_small_blind_57.setMinimum(0)
        self.slider_small_blind_57.setMaximum(5)
        self.slider_small_blind_57.setPageStep(1)
        self.slider_small_blind_57.setOrientation(QtCore.Qt.Horizontal)
        self.slider_small_blind_57.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_small_blind_57.setObjectName("slider_small_blind_57")
        self.verticalLayout_138.addWidget(self.slider_small_blind_57)
        self.gridLayout_6.addLayout(self.verticalLayout_138, 7, 2, 1, 1)
        self.lcdNumber_50 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_50.setObjectName("lcdNumber_50")
        self.gridLayout_6.addWidget(self.lcdNumber_50, 7, 3, 1, 1)
        self.verticalLayout_136 = QtWidgets.QVBoxLayout()
        self.verticalLayout_136.setObjectName("verticalLayout_136")
        self.label_131 = QtWidgets.QLabel(self.tab)
        self.label_131.setObjectName("label_131")
        self.verticalLayout_136.addWidget(self.label_131)
        self.RiverBluffMinEquity = QtWidgets.QSlider(self.tab)
        self.RiverBluffMinEquity.setMouseTracking(False)
        self.RiverBluffMinEquity.setMinimum(1)
        self.RiverBluffMinEquity.setMaximum(100)
        self.RiverBluffMinEquity.setSingleStep(1)
        self.RiverBluffMinEquity.setPageStep(5)
        self.RiverBluffMinEquity.setProperty("value", 50)
        self.RiverBluffMinEquity.setOrientation(QtCore.Qt.Horizontal)
        self.RiverBluffMinEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RiverBluffMinEquity.setObjectName("RiverBluffMinEquity")
        self.verticalLayout_136.addWidget(self.RiverBluffMinEquity)
        self.gridLayout_6.addLayout(self.verticalLayout_136, 8, 0, 1, 1)
        self.lcdNumber_51 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_51.setObjectName("lcdNumber_51")
        self.gridLayout_6.addWidget(self.lcdNumber_51, 8, 1, 1, 1)
        self.verticalLayout_135 = QtWidgets.QVBoxLayout()
        self.verticalLayout_135.setObjectName("verticalLayout_135")
        self.label_130 = QtWidgets.QLabel(self.tab)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_135.addWidget(self.label_130)
        self.slider_small_blind_56 = QtWidgets.QSlider(self.tab)
        self.slider_small_blind_56.setEnabled(False)
        self.slider_small_blind_56.setMouseTracking(False)
        self.slider_small_blind_56.setMinimum(1)
        self.slider_small_blind_56.setMaximum(10)
        self.slider_small_blind_56.setPageStep(1)
        self.slider_small_blind_56.setOrientation(QtCore.Qt.Horizontal)
        self.slider_small_blind_56.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_small_blind_56.setObjectName("slider_small_blind_56")
        self.verticalLayout_135.addWidget(self.slider_small_blind_56)
        self.gridLayout_6.addLayout(self.verticalLayout_135, 8, 2, 1, 1)
        self.lcdNumber_49 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_49.setObjectName("lcdNumber_49")
        self.gridLayout_6.addWidget(self.lcdNumber_49, 8, 3, 1, 1)
        self.verticalLayout_131 = QtWidgets.QVBoxLayout()
        self.verticalLayout_131.setObjectName("verticalLayout_131")
        self.label_126 = QtWidgets.QLabel(self.tab)
        self.label_126.setObjectName("label_126")
        self.verticalLayout_131.addWidget(self.label_126)
        self.betPotRiverEquity = QtWidgets.QSlider(self.tab)
        self.betPotRiverEquity.setMouseTracking(False)
        self.betPotRiverEquity.setMinimum(70)
        self.betPotRiverEquity.setMaximum(100)
        self.betPotRiverEquity.setSingleStep(1)
        self.betPotRiverEquity.setPageStep(1)
        self.betPotRiverEquity.setProperty("value", 70)
        self.betPotRiverEquity.setOrientation(QtCore.Qt.Horizontal)
        self.betPotRiverEquity.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.betPotRiverEquity.setObjectName("betPotRiverEquity")
        self.verticalLayout_131.addWidget(self.betPotRiverEquity)
        self.gridLayout_6.addLayout(self.verticalLayout_131, 9, 0, 1, 1)
        self.lcdNumber_53 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_53.setObjectName("lcdNumber_53")
        self.gridLayout_6.addWidget(self.lcdNumber_53, 9, 1, 1, 1)
        self.verticalLayout_380 = QtWidgets.QVBoxLayout()
        self.verticalLayout_380.setObjectName("verticalLayout_380")
        self.label_393 = QtWidgets.QLabel(self.tab)
        self.label_393.setObjectName("label_393")
        self.verticalLayout_380.addWidget(self.label_393)
        self.betPotRiverEquityMaxBBM = QtWidgets.QSlider(self.tab)
        self.betPotRiverEquityMaxBBM.setMouseTracking(False)
        self.betPotRiverEquityMaxBBM.setMinimum(1)
        self.betPotRiverEquityMaxBBM.setMaximum(5)
        self.betPotRiverEquityMaxBBM.setPageStep(1)
        self.betPotRiverEquityMaxBBM.setOrientation(QtCore.Qt.Horizontal)
        self.betPotRiverEquityMaxBBM.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.betPotRiverEquityMaxBBM.setObjectName("betPotRiverEquityMaxBBM")
        self.verticalLayout_380.addWidget(self.betPotRiverEquityMaxBBM)
        self.gridLayout_6.addLayout(self.verticalLayout_380, 9, 2, 1, 1)
        self.lcdNumber_60 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_60.setObjectName("lcdNumber_60")
        self.gridLayout_6.addWidget(self.lcdNumber_60, 9, 3, 1, 1)
        self.pushButton_update4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_update4.setObjectName("pushButton_update4")
        self.gridLayout_6.addWidget(self.pushButton_update4, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.pokerSite = QtWidgets.QComboBox(self.tab_5)
        self.pokerSite.setObjectName("pokerSite")
        self.verticalLayout_7.addWidget(self.pokerSite)
        self.gridLayout_7.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.smallBlind = QtWidgets.QSlider(self.tab_5)
        self.smallBlind.setMouseTracking(False)
        self.smallBlind.setMinimum(1)
        self.smallBlind.setMaximum(500)
        self.smallBlind.setPageStep(10)
        self.smallBlind.setOrientation(QtCore.Qt.Horizontal)
        self.smallBlind.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.smallBlind.setObjectName("smallBlind")
        self.verticalLayout_5.addWidget(self.smallBlind)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.lcdNumber_62 = QtWidgets.QLCDNumber(self.tab_5)
        self.lcdNumber_62.setObjectName("lcdNumber_62")
        self.gridLayout_7.addWidget(self.lcdNumber_62, 1, 1, 1, 1)
        self.verticalLayout_437 = QtWidgets.QVBoxLayout()
        self.verticalLayout_437.setObjectName("verticalLayout_437")
        self.label_454 = QtWidgets.QLabel(self.tab_5)
        self.label_454.setObjectName("label_454")
        self.verticalLayout_437.addWidget(self.label_454)
        self.bigBlind = QtWidgets.QSlider(self.tab_5)
        self.bigBlind.setMouseTracking(False)
        self.bigBlind.setMinimum(2)
        self.bigBlind.setMaximum(1000)
        self.bigBlind.setPageStep(10)
        self.bigBlind.setOrientation(QtCore.Qt.Horizontal)
        self.bigBlind.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.bigBlind.setObjectName("bigBlind")
        self.verticalLayout_437.addWidget(self.bigBlind)
        self.gridLayout_7.addLayout(self.verticalLayout_437, 2, 0, 1, 1)
        self.lcdNumber_114 = QtWidgets.QLCDNumber(self.tab_5)
        self.lcdNumber_114.setObjectName("lcdNumber_114")
        self.gridLayout_7.addWidget(self.lcdNumber_114, 2, 1, 1, 1)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_32.addWidget(self.label_37)
        self.initialFunds = QtWidgets.QSlider(self.tab_5)
        self.initialFunds.setMouseTracking(False)
        self.initialFunds.setMinimum(1)
        self.initialFunds.setMaximum(500)
        self.initialFunds.setPageStep(10)
        self.initialFunds.setOrientation(QtCore.Qt.Horizontal)
        self.initialFunds.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.initialFunds.setObjectName("initialFunds")
        self.verticalLayout_32.addWidget(self.initialFunds)
        self.gridLayout_7.addLayout(self.verticalLayout_32, 3, 0, 1, 1)
        self.lcdNumber_61 = QtWidgets.QLCDNumber(self.tab_5)
        self.lcdNumber_61.setObjectName("lcdNumber_61")
        self.gridLayout_7.addWidget(self.lcdNumber_61, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 13, 0, 1, 3)

        self.retranslateUi(editor_form)
        self.tabWidget.setCurrentIndex(0)
        self.alwaysCallEquity.valueChanged['int'].connect(self.lcdNumber_57.display)
        self.potAdjustmentPreFlop.valueChanged['int'].connect(self.lcdNumber_17.display)
        self.FlopMinCallEquity.valueChanged['int'].connect(self.lcdNumber_34.display)
        self.FlopCallPower.valueChanged['int'].connect(self.lcdNumber_29.display)
        self.FlopMinBetEquity.valueChanged['int'].connect(self.lcdNumber_36.display)
        self.TurnCallPower.valueChanged['int'].connect(self.lcdNumber_38.display)
        self.potAdjustment.valueChanged['int'].connect(self.lcdNumber_32.display)
        self.TurnMinBetEquity.valueChanged['int'].connect(self.lcdNumber_45.display)
        self.PreFlopMinBetEquity.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.PreFlopBetPower.valueChanged['int'].connect(self.lcdNumber_4.display)
        self.CoveredPlayersCallLikelihoodPreFlop.valueChanged['int'].connect(self.lcdNumber_9.display)
        self.bullyDivider.valueChanged['int'].connect(self.lcdNumber_58.display)
        self.CoveredPlayersCallLikelihoodFlop.valueChanged['int'].connect(self.lcdNumber_30.display)
        self.FlopBetPower.valueChanged['int'].connect(self.lcdNumber_28.display)
        self.RiverMinCallEquity.valueChanged['int'].connect(self.lcdNumber_52.display)
        self.secondRoundAdjustmentPreFlop.valueChanged['int'].connect(self.lcdNumber_16.display)
        self.FlopBluffMinEquity.valueChanged['int'].connect(self.lcdNumber_33.display)
        self.maxBullyEquity.valueChanged['int'].connect(self.lcdNumber_59.display)
        self.BetPlusInc.valueChanged['int'].connect(self.lcdNumber_56.display)
        self.maxPotAdjustment.valueChanged['int'].connect(self.lcdNumber_31.display)
        self.TurnMinCallEquity.valueChanged['int'].connect(self.lcdNumber_43.display)
        self.PreFlopMinCallEquity.valueChanged['int'].connect(self.lcdNumber.display)
        self.minBullyEquity.valueChanged['int'].connect(self.lcdNumber_55.display)
        self.PreFlopCallPower.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.slider_FlopBluffMinEquity.valueChanged['int'].connect(self.lcdNumber_15.display)
        self.maxPotAdjustmentPreFlop.valueChanged['int'].connect(self.lcdNumber_18.display)
        self.PreFlopMaxBetEquity.valueChanged['int'].connect(self.lcdNumber_63.display)
        self.RiverCallPower.valueChanged['int'].connect(self.lcdNumber_47.display)
        self.initialFunds.valueChanged['int'].connect(self.lcdNumber_61.display)
        self.considerLastGames.valueChanged['int'].connect(self.lcdNumber_112.display)
        self.secondRiverBetPotMinEquity.valueChanged['int'].connect(self.lcdNumber_48.display)
        self.strategyIterationGames.valueChanged['int'].connect(self.lcdNumber_113.display)
        self.TurnBluffMinEquity.valueChanged['int'].connect(self.lcdNumber_42.display)
        self.slider_small_blind_57.valueChanged['int'].connect(self.lcdNumber_50.display)
        self.bigBlind.valueChanged['int'].connect(self.lcdNumber_114.display)
        self.secondRoundAdjustmentPowerIncrease.valueChanged['int'].connect(self.lcdNumber_111.display)
        self.slider_small_blind_51.valueChanged['int'].connect(self.lcdNumber_41.display)
        self.smallBlind.valueChanged['int'].connect(self.lcdNumber_62.display)
        self.minimumLossForIteration.valueChanged['int'].connect(self.lcdNumber_109.display)
        self.RiverBetPower.valueChanged['int'].connect(self.lcdNumber_46.display)
        self.betPotRiverEquity.valueChanged['int'].connect(self.lcdNumber_53.display)
        self.RiverMinBetEquity.valueChanged['int'].connect(self.lcdNumber_54.display)
        self.slider_small_blind_56.valueChanged['int'].connect(self.lcdNumber_49.display)
        self.slider_small_blind_50.valueChanged['int'].connect(self.lcdNumber_40.display)
        self.TurnBetPower.valueChanged['int'].connect(self.lcdNumber_37.display)
        self.betPotRiverEquityMaxBBM.valueChanged['int'].connect(self.lcdNumber_60.display)
        self.FlopCheckDeceptionMinEquity.valueChanged['int'].connect(self.lcdNumber_110.display)
        self.RiverBluffMinEquity.valueChanged['int'].connect(self.lcdNumber_51.display)
        self.secondRoundAdjustment.valueChanged['int'].connect(self.lcdNumber_35.display)
        QtCore.QMetaObject.connectSlotsByName(editor_form)

    def retranslateUi(self, editor_form):
        _translate = QtCore.QCoreApplication.translate
        editor_form.setWindowTitle(_translate("editor_form", "Strategy editor"))
        self.label_4.setText(_translate("editor_form", "Strategy editor"))
        self.label.setText(_translate("editor_form", "Select Strategy"))
        self.Strategy.setToolTip(_translate("editor_form", "Select a strategy you want to edit"))
        self.pushButton_save_current_strategy.setToolTip(_translate("editor_form", "You can only save strategies you have created yourself. Otherwise save it under a new name."))
        self.pushButton_save_current_strategy.setText(_translate("editor_form", "Save"))
        self.label_2.setText(_translate("editor_form", "New name"))
        self.pushButton_save_new_strategy.setToolTip(_translate("editor_form", "Saves the current strategy under a new name"))
        self.pushButton_save_new_strategy.setText(_translate("editor_form", "Save under new name"))
        self.tabWidget.setToolTip(_translate("editor_form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_32.setText(_translate("editor_form", "Equity threshold above which everything is called"))
        self.label_20.setText(_translate("editor_form", "Bet Plus: how many times the + is pressed to increase the bet"))
        self.BetPlusInc.setToolTip(_translate("editor_form", "<html><head/><body><p>When the bot decides a simple press on the bet button is not enough, it can do a \'betPlus\'. That means it will shift the slider to the right with x clicks and then only press the bet button. Here you can adjust how many times it should click to slide the slider to the right to increase the bet size.</p></body></html>"))
        self.label_12.setText(_translate("editor_form", "Bullying when heads up opponent stacks are below value, original funds divided by:"))
        self.bullyDivider.setToolTip(_translate("editor_form", "<html><head/><body><p>In headsup when the single opponent has less than a certain amount of stacks left, the bot can be more agressive. This is activated when he has less funds than initial funds divided by the divider (which is this slide). For example for initial funds of $2 and a divider of 4, the bot would become more agressive if the opponent has less than $0.50.</p></body></html>"))
        self.label_38.setText(_translate("editor_form", "Minimum required equity to bully"))
        self.minBullyEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>In order activate bully mode (meaning the bot is more aggressive), a minimum amounf of equity (winning probability as determined by the simulation) can be selected.</p></body></html>"))
        self.label_39.setText(_translate("editor_form", "Maximum equity to bully"))
        self.maxBullyEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>Upper limit of equity where bully mode can be activated if all conditions are met.</p></body></html>"))
        self.label_449.setText(_translate("editor_form", "Minimum loss to initiate Genetic Algorithm"))
        self.label_452.setText(_translate("editor_form", "Considering the last # of games and initiating the algorithm ever # of rounds"))
        self.considerLastGames.setToolTip(_translate("editor_form", "<html><head/><body><p>The genetic algorithm can be activated automatically. Here you can select under what conditions this will happen. It only makes sens to have it activated after playing at least 500 hands.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generic), _translate("editor_form", "General"))
        self.label_36.setText(_translate("editor_form", "Maximum pot adjustment"))
        self.maxPotAdjustmentPreFlop.setToolTip(_translate("editor_form", "If the pot becomes extremely high, the adjustment can be limited."))
        self.label_33.setText(_translate("editor_form", "Second round adjustment in equity for preflop"))
        self.secondRoundAdjustmentPreFlop.setToolTip(_translate("editor_form", "<html><head/><body><p>If the bot has called or made a bet and then one of the following players raises, another round is played. This is called the \'second round\'. It is sometimes a sign that one of the opponents has good cards, that\'s why it\'s possible to make an adjustment and increase the minimum amount of equity that is required to call or bet, so the bot becomes more conservative.</p></body></html>"))
        self.label_35.setText(_translate("editor_form", "Pot adjustment"))
        self.potAdjustmentPreFlop.setToolTip(_translate("editor_form", "If the pot gets bigger, the bot becomes more agressive. This slider can adjust how more agressive it should become. "))
        self.label_18.setText(_translate("editor_form", "% Likelyhood following players will call"))
        self.CoveredPlayersCallLikelihoodPreFlop.setToolTip(_translate("editor_form", "<html><head/><body><p>To calculate the equity (winning probability with given cards), the bot runs a simulation of around 20000 games with the given cards (your cards and the cards on the table) and then counts how many times it won, giving random cards to all other players. However, it is not clear how many players will be in the game. The minimum is always 2 (yourself and one opponent) but it can be more. The bot assumes that the amount of players is always yourself, all players that have played in this round and did not fold + the players that are still to act in this round * probability they will call. If you put it to 0. In zoom / fast forward games this is ususually quite low as only around 20% of the players make it to the flop. In other types of games this may be higher.</p></body></html>"))
        self.label_19.setText(_translate("editor_form", "Minimum equity required to potentially bluff"))
        self.slider_FlopBluffMinEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>The bot has the ability to bluff (pressing the bet button even though the required equity is not met). This is currently done under the following circumstances:</p><p>1. Nobody has bet, so there must be a check button</p><p>2. In the last stage there was a check button as well (so nobody bet)</p><p>3. The minimum equity is met as selected in this slider (this will be lower than the minimum required equity selected at the top)</p></body></html>"))
        self.label_3.setText(_translate("editor_form", "Calling"))
        self.label_237.setText(_translate("editor_form", "Minimum required equity"))
        self.PreFlopMinCallEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_394.setText(_translate("editor_form", "Maximum equity to bet"))
        self.PreFlopMaxBetEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>At the preflop stage you can set a maximum equity where the bot will bet. This is useful for tables where the players are very conservative and get scared easily. So you can avoid giving a way having good preflop cards and not bet (only call assuming you are still on the right of the blue curve). The red curve will break off at this point.</p></body></html>"))
        self.label_6.setText(_translate("editor_form", "Betting"))
        self.label_15.setText(_translate("editor_form", "Curvature"))
        self.PreFlopCallPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_16.setText(_translate("editor_form", "Minimum required equity"))
        self.PreFlopMinBetEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_17.setText(_translate("editor_form", "Curvature"))
        self.PreFlopBetPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_451.setText(_translate("editor_form", "Second Round adjustment curvature increase (all stages)"))
        self.secondRoundAdjustmentPowerIncrease.setToolTip(_translate("editor_form", "<html><head/><body><p>If the bot has called or made a bet and then one of the following players raises, another round is played. This is called the \'second round\'. It is sometimes a sign that one of the opponents has good cards, that\'s why it\'s possible to make an adjustment and increase the curvature of the betting and calling limit, so the bot becomes more conservative.</p></body></html>", " "))
        self.widget_4.setToolTip(_translate("editor_form", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_update1.setText(_translate("editor_form", "Update Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PreFlop), _translate("editor_form", "PreFlop automatic"))
        self.preflop_override.setText(_translate("editor_form", "Use manual preflop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("editor_form", "PreFlop manual"))
        self.label_450.setText(_translate("editor_form", "Check deception if equity is above treshold"))
        self.FlopCheckDeceptionMinEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>If the equity is very high, you may not want to be aggresssive at the flop stage already. That\'s why you may simply want to check or call, instead of making a big bet. For example if you suddenly have a 90% equity, you can set the limit here above which amount of equity you want to do a \'check deception\' at the flop.</p></body></html>"))
        self.label_177.setText(_translate("editor_form", "Second round adjustment in minimum equty Flop, Turn, River"))
        self.label_175.setText(_translate("editor_form", "Calling"))
        self.label_179.setText(_translate("editor_form", "Minimum required equity"))
        self.FlopMinCallEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_182.setText(_translate("editor_form", "Minimum required equity"))
        self.FlopMinBetEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_184.setText(_translate("editor_form", "Betting"))
        self.label_180.setText(_translate("editor_form", "Curvature"))
        self.FlopCallPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_176.setText(_translate("editor_form", "Curvature"))
        self.FlopBetPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_178.setText(_translate("editor_form", "% Likelyhood following players will call"))
        self.label_185.setText(_translate("editor_form", "Pot adjustment"))
        self.label_183.setText(_translate("editor_form", "Minimum equity required to potentially bluff"))
        self.label_181.setText(_translate("editor_form", "Maximum pot adjustment"))
        self.pushButton_update2.setText(_translate("editor_form", "Update Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("editor_form", "Flop"))
        self.label_9.setText(_translate("editor_form", "Calling"))
        self.label_109.setText(_translate("editor_form", "Minimum required equity"))
        self.TurnMinCallEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_111.setText(_translate("editor_form", "Curvature"))
        self.TurnCallPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_235.setText(_translate("editor_form", "Betting"))
        self.label_114.setText(_translate("editor_form", "Minimum required equity"))
        self.TurnMinBetEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_107.setText(_translate("editor_form", "Curvature"))
        self.TurnBetPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_115.setText(_translate("editor_form", "Pot adjustment"))
        self.label_113.setText(_translate("editor_form", "Minimum equity required to potentially bluff"))
        self.label_112.setText(_translate("editor_form", "Maximum pot adjustment"))
        self.pushButton_update3.setText(_translate("editor_form", "Update Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WorstGames), _translate("editor_form", "Turn"))
        self.label_10.setText(_translate("editor_form", "Calling"))
        self.label_127.setText(_translate("editor_form", "Minimum required equity"))
        self.RiverMinCallEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_129.setText(_translate("editor_form", "Curvature"))
        self.RiverCallPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) that is required to call the big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_236.setText(_translate("editor_form", "Betting"))
        self.label_132.setText(_translate("editor_form", "Minimum required equity"))
        self.RiverMinBetEquity.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_125.setText(_translate("editor_form", "Curvature"))
        self.RiverBetPower.setToolTip(_translate("editor_form", "<html><head/><body><p>For each stage you can select:</p><p>What is the minimum required equity (probability of winning as determined by the simulation) to make a bet, if the bet value is 2*big blind. It is the starting point of the curve that you can see on the right.</p><p>How should curve be shaped that determines whether the bot should fold or call. The higher the equity the higher it will call. The higher the curvature (as can be seen in the graph on the right), the more conservative it will be on the lower ranges of the accepted equities. If the curvature is low (minimum is 2), then it almost becomes a straight line.</p></body></html>"))
        self.label_128.setText(_translate("editor_form", "Second Round Minimum equity to bet full pot"))
        self.label_133.setText(_translate("editor_form", "Pot adjustment"))
        self.label_131.setText(_translate("editor_form", "Minimum equity required to potentially bluff"))
        self.label_130.setText(_translate("editor_form", "Maximum pot adjustment"))
        self.label_126.setText(_translate("editor_form", "Minimum required equity to bet full pot"))
        self.label_393.setText(_translate("editor_form", "Bet Pot River Equity Max Big blind multiplier"))
        self.pushButton_update4.setText(_translate("editor_form", "Update Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("editor_form", "River"))
        self.label_13.setText(_translate("editor_form", "Poker Site (Party Poker or Poker Stars)"))
        self.pokerSite.setToolTip(_translate("editor_form", "Currently Partypoker (PP) and Pokerstars (PS) are supported"))
        self.label_11.setText(_translate("editor_form", "Small Blind (cents)"))
        self.label_454.setText(_translate("editor_form", "Big Blind (cents)"))
        self.label_37.setText(_translate("editor_form", "Initial fundsBlind (cents)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("editor_form", "Table Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editor_form = QtWidgets.QWidget()
    ui = Ui_editor_form()
    ui.setupUi(editor_form)
    editor_form.show()
    sys.exit(app.exec_())

