# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT_ui_analyser.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(722, 748)
        Form.setMinimumSize(QtCore.QSize(722, 748))
        Form.setMaximumSize(QtCore.QSize(722, 748))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combobox_strategy = QtWidgets.QComboBox(Form)
        self.combobox_strategy.setObjectName("combobox_strategy")
        self.horizontalLayout.addWidget(self.combobox_strategy)
        self.combobox_gamestage = QtWidgets.QComboBox(Form)
        self.combobox_gamestage.setObjectName("combobox_gamestage")
        self.horizontalLayout.addWidget(self.combobox_gamestage)
        self.combobox_actiontype = QtWidgets.QComboBox(Form)
        self.combobox_actiontype.setObjectName("combobox_actiontype")
        self.horizontalLayout.addWidget(self.combobox_actiontype)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 4, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 4, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.EquityHistogram = QtWidgets.QWidget()
        self.EquityHistogram.setObjectName("EquityHistogram")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.EquityHistogram)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 261, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_bar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_bar.setObjectName("vLayout_bar")
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.vLayout_bar.addWidget(self.widget_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.EquityHistogram)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 140, 411, 411))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.EquityHistogram)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 681, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vLayout_fundschange = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vLayout_fundschange.setObjectName("vLayout_fundschange")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.vLayout_fundschange.addWidget(self.widget)
        self.tabWidget.addTab(self.EquityHistogram, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.WorstGames = QtWidgets.QWidget()
        self.WorstGames.setObjectName("WorstGames")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WorstGames)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.WorstGames)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.WorstGames, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Strategy Analyser"))
        self.label_4.setText(_translate("Form", "Strategy Analyser"))
        self.label.setText(_translate("Form", "Strategy"))
        self.label_2.setText(_translate("Form", "Game Stage"))
        self.label_3.setText(_translate("Form", "Action Type"))
        self.combobox_strategy.setToolTip(_translate("Form", "<html><head/><body><p>Choose the strategy you would like to analyse. \'.*\' means all strategies together.</p></body></html>"))
        self.combobox_gamestage.setToolTip(_translate("Form", "Choose the game stage you want to focus on."))
        self.combobox_actiontype.setToolTip(_translate("Form", "Choose what kind of decision you want to analyse in more detail."))
        self.label_6.setText(_translate("Form", "Total played hands"))
        self.label_5.setText(_translate("Form", "Return in bb per 100 hands"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EquityHistogram), _translate("Form", "Equity Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Scatter Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WorstGames), _translate("Form", "Worst Hands"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

