# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT_ui_analyser.ui'
#
# Created: Thu Aug 25 03:31:54 2016
#      by: pyside-uic 0.2.15 running on PyQt4 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 748)
        Form.setMinimumSize(QtCore.QSize(722, 748))
        Form.setMaximumSize(QtCore.QSize(722, 748))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(250, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 160, 691, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.EquityHistogram = QtGui.QWidget()
        self.EquityHistogram.setObjectName("EquityHistogram")
        self.verticalLayoutWidget = QtGui.QWidget(self.EquityHistogram)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 261, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_bar = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_bar.setContentsMargins(0, 0, 0, 0)
        self.vLayout_bar.setObjectName("vLayout_bar")
        self.widget_2 = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.vLayout_bar.addWidget(self.widget_2)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.EquityHistogram)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 140, 411, 411))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtGui.QWidget(self.horizontalLayoutWidget_3)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.EquityHistogram)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 681, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vLayout_fundschange = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vLayout_fundschange.setContentsMargins(0, 0, 0, 0)
        self.vLayout_fundschange.setObjectName("vLayout_fundschange")
        self.widget = QtGui.QWidget(self.verticalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.vLayout_fundschange.addWidget(self.widget)
        self.tabWidget.addTab(self.EquityHistogram, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 661, 531))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 100, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 681, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lcdNumber_2 = QtGui.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 120, 91, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 681, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combobox_strategy = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.combobox_strategy.setObjectName("combobox_strategy")
        self.horizontalLayout.addWidget(self.combobox_strategy)
        self.combobox_gamestage = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.combobox_gamestage.setObjectName("combobox_gamestage")
        self.horizontalLayout.addWidget(self.combobox_gamestage)
        self.combobox_actiontype = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.combobox_actiontype.setObjectName("combobox_actiontype")
        self.horizontalLayout.addWidget(self.combobox_actiontype)
        self.lcdNumber = QtGui.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 120, 121, 31))
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Strategy Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EquityHistogram), QtGui.QApplication.translate("Form", "Equity Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Scatter Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Return per game per small blind ($0.02)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Total hads", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Strategy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Game Stage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Action Type", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

