# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_qt_ui.ui'
#
# Created: Mon Aug  8 02:28:11 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 885)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(620, 290, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(215, 220, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.status.setFont(font)
        self.status.setFrameShape(QtGui.QFrame.Panel)
        self.status.setFrameShadow(QtGui.QFrame.Sunken)
        self.status.setScaledContents(False)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setMargin(1)
        self.status.setIndent(-1)
        self.status.setObjectName("status")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 290, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 211, 181))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 600, 321, 241))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vLayout2_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vLayout2_2.setContentsMargins(0, 0, 0, 0)
        self.vLayout2_2.setObjectName("vLayout2_2")
        self.mplv2_2 = QtGui.QWidget(self.verticalLayoutWidget_3)
        self.mplv2_2.setObjectName("mplv2_2")
        self.vLayout2_2.addWidget(self.mplv2_2)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 321, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout.setContentsMargins(0, 0, 0, 0)
        self.vLayout.setObjectName("vLayout")
        self.mplvl = QtGui.QWidget(self.verticalLayoutWidget)
        self.mplvl.setObjectName("mplvl")
        self.vLayout.addWidget(self.mplvl)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(360, 330, 321, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vLayout2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vLayout2.setContentsMargins(0, 0, 0, 0)
        self.vLayout2.setObjectName("vLayout2")
        self.mplv2 = QtGui.QWidget(self.verticalLayoutWidget_2)
        self.mplv2.setMouseTracking(False)
        self.mplv2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mplv2.setObjectName("mplv2")
        self.vLayout2.addWidget(self.mplv2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(210, 260, 281, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 290, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 290, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(360, 30, 211, 181))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(230, 30, 91, 181))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcdNumber_3 = QtGui.QLCDNumber(self.verticalLayoutWidget_5)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_3.addWidget(self.lcdNumber_3)
        self.lcdNumber = QtGui.QLCDNumber(self.verticalLayoutWidget_5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_3.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.verticalLayoutWidget_5)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_3.addWidget(self.lcdNumber_2)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.verticalLayoutWidget_5)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_3.addWidget(self.lcdNumber_4)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.verticalLayoutWidget_5)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.verticalLayout_3.addWidget(self.lcdNumber_5)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 290, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(580, 30, 91, 181))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lcdNumber_6 = QtGui.QLCDNumber(self.verticalLayoutWidget_8)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.verticalLayout_6.addWidget(self.lcdNumber_6)
        self.lcdNumber_7 = QtGui.QLCDNumber(self.verticalLayoutWidget_8)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.verticalLayout_6.addWidget(self.lcdNumber_7)
        self.lcdNumber_8 = QtGui.QLCDNumber(self.verticalLayoutWidget_8)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.verticalLayout_6.addWidget(self.lcdNumber_8)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.verticalLayoutWidget_8)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.verticalLayout_6.addWidget(self.lcdNumber_9)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.verticalLayoutWidget_8)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.verticalLayout_6.addWidget(self.lcdNumber_10)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(360, 600, 321, 241))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vLayout2_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vLayout2_3.setContentsMargins(0, 0, 0, 0)
        self.vLayout2_3.setObjectName("vLayout2_3")
        self.mplv2_3 = QtGui.QWidget(self.verticalLayoutWidget_4)
        self.mplv2_3.setObjectName("mplv2_3")
        self.vLayout2_3.addWidget(self.mplv2_3)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 27))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Autoplay", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run AI", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

