# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_QT_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pokerbot(object):
    def setupUi(self, Pokerbot):
        Pokerbot.setObjectName("Pokerbot")
        Pokerbot.resize(617, 713)
        Pokerbot.setMinimumSize(QtCore.QSize(617, 713))
        Pokerbot.setMaximumSize(QtCore.QSize(617, 713))
        font = QtGui.QFont()
        font.setPointSize(12)
        Pokerbot.setFont(font)
        Pokerbot.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Pokerbot)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.assumed_players = QtWidgets.QLCDNumber(self.centralwidget)
        self.assumed_players.setObjectName("assumed_players")
        self.verticalLayout_6.addWidget(self.assumed_players)
        self.required_mincall = QtWidgets.QLCDNumber(self.centralwidget)
        self.required_mincall.setObjectName("required_mincall")
        self.verticalLayout_6.addWidget(self.required_mincall)
        self.required_minbet = QtWidgets.QLCDNumber(self.centralwidget)
        self.required_minbet.setObjectName("required_minbet")
        self.verticalLayout_6.addWidget(self.required_minbet)
        self.zero_ev = QtWidgets.QLCDNumber(self.centralwidget)
        self.zero_ev.setObjectName("zero_ev")
        self.verticalLayout_6.addWidget(self.zero_ev)
        self.winnings = QtWidgets.QLCDNumber(self.centralwidget)
        self.winnings.setObjectName("winnings")
        self.verticalLayout_6.addWidget(self.winnings)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 5, 1, 1)
        self.vLayout = QtWidgets.QVBoxLayout()
        self.vLayout.setObjectName("vLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.vLayout.addWidget(self.widget_3)
        self.gridLayout.addLayout(self.vLayout, 8, 0, 1, 3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_5, 3, 3, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 0, 1, 2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_pause.setFont(font)
        self.button_pause.setObjectName("button_pause")
        self.verticalLayout_7.addWidget(self.button_pause)
        self.button_resume = QtWidgets.QPushButton(self.centralwidget)
        self.button_resume.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_resume.setFont(font)
        self.button_resume.setObjectName("button_resume")
        self.verticalLayout_7.addWidget(self.button_resume)
        self.button_log_analyser = QtWidgets.QPushButton(self.centralwidget)
        self.button_log_analyser.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_log_analyser.setFont(font)
        self.button_log_analyser.setObjectName("button_log_analyser")
        self.verticalLayout_7.addWidget(self.button_log_analyser)
        self.button_strategy_editor = QtWidgets.QPushButton(self.centralwidget)
        self.button_strategy_editor.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_strategy_editor.setFont(font)
        self.button_strategy_editor.setObjectName("button_strategy_editor")
        self.verticalLayout_7.addWidget(self.button_strategy_editor)
        self.button_genetic_algorithm = QtWidgets.QPushButton(self.centralwidget)
        self.button_genetic_algorithm.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_genetic_algorithm.setFont(font)
        self.button_genetic_algorithm.setObjectName("button_genetic_algorithm")
        self.verticalLayout_7.addWidget(self.button_genetic_algorithm)
        self.gridLayout.addLayout(self.verticalLayout_7, 5, 0, 1, 3)
        self.vLayout2 = QtWidgets.QVBoxLayout()
        self.vLayout2.setObjectName("vLayout2")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.vLayout2.addWidget(self.widget_4)
        self.gridLayout.addLayout(self.vLayout2, 8, 3, 1, 3)
        self.vLayout4 = QtWidgets.QVBoxLayout()
        self.vLayout4.setObjectName("vLayout4")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.vLayout4.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.vLayout4, 9, 3, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.last_decision = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.last_decision.setFont(font)
        self.last_decision.setAutoFillBackground(False)
        self.last_decision.setFrameShape(QtWidgets.QFrame.Panel)
        self.last_decision.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.last_decision.setScaledContents(False)
        self.last_decision.setAlignment(QtCore.Qt.AlignCenter)
        self.last_decision.setIndent(-1)
        self.last_decision.setObjectName("last_decision")
        self.gridLayout_2.addWidget(self.last_decision, 2, 0, 1, 1)
        self.comboBox_current_strategy = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_current_strategy.setFont(font)
        self.comboBox_current_strategy.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_current_strategy.setObjectName("comboBox_current_strategy")
        self.gridLayout_2.addWidget(self.comboBox_current_strategy, 6, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status.setFont(font)
        self.status.setToolTip("")
        self.status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 4, 0, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout_2.addWidget(self.progress_bar, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 3, 1, 3)
        self.vLayout3 = QtWidgets.QVBoxLayout()
        self.vLayout3.setObjectName("vLayout3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.vLayout3.addWidget(self.widget)
        self.gridLayout.addLayout(self.vLayout3, 9, 0, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.equity = QtWidgets.QLCDNumber(self.centralwidget)
        self.equity.setObjectName("equity")
        self.verticalLayout_3.addWidget(self.equity)
        self.calllimit = QtWidgets.QLCDNumber(self.centralwidget)
        self.calllimit.setObjectName("calllimit")
        self.verticalLayout_3.addWidget(self.calllimit)
        self.betlimit = QtWidgets.QLCDNumber(self.centralwidget)
        self.betlimit.setObjectName("betlimit")
        self.verticalLayout_3.addWidget(self.betlimit)
        self.potsize = QtWidgets.QLCDNumber(self.centralwidget)
        self.potsize.setObjectName("potsize")
        self.verticalLayout_3.addWidget(self.potsize)
        self.gamenumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.gamenumber.setObjectName("gamenumber")
        self.verticalLayout_3.addWidget(self.gamenumber)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 2, 1, 1)
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setObjectName("pushButton_help")
        self.gridLayout.addWidget(self.pushButton_help, 0, 5, 1, 1)
        self.pushButton_setup = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_setup.setFont(font)
        self.pushButton_setup.setObjectName("pushButton_setup")
        self.gridLayout.addWidget(self.pushButton_setup, 0, 0, 1, 1)
        Pokerbot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Pokerbot)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Pokerbot.setStatusBar(self.statusbar)

        self.retranslateUi(Pokerbot)
        QtCore.QMetaObject.connectSlotsByName(Pokerbot)

    def retranslateUi(self, Pokerbot):
        _translate = QtCore.QCoreApplication.translate
        Pokerbot.setWindowTitle(_translate("Pokerbot", "Pokerbot"))
        self.label_11.setText(_translate("Pokerbot", "DeepMind PokerBot"))
        self.assumed_players.setToolTip(_translate("Pokerbot", "To calculate the equity (winning probability), the simulation assumes this amount of players in the game (including yourself)"))
        self.required_mincall.setToolTip(_translate("Pokerbot", "$ on the call button"))
        self.required_minbet.setToolTip(_translate("Pokerbot", "$ on the bet button"))
        self.label_6.setText(_translate("Pokerbot", "Assumed players"))
        self.label_7.setText(_translate("Pokerbot", "Required minimum call"))
        self.label_8.setText(_translate("Pokerbot", "Required minimum bet"))
        self.label_9.setText(_translate("Pokerbot", "Zero EV Call"))
        self.label_10.setText(_translate("Pokerbot", "Last 500 hands return"))
        self.label_2.setText(_translate("Pokerbot", "Equity (winning probability)"))
        self.label_3.setText(_translate("Pokerbot", "Final call limit"))
        self.label_4.setText(_translate("Pokerbot", "Final bet Limit"))
        self.label_5.setText(_translate("Pokerbot", "Pot Size"))
        self.label.setText(_translate("Pokerbot", "Hand number"))
        self.button_pause.setText(_translate("Pokerbot", "Pause"))
        self.button_resume.setText(_translate("Pokerbot", "Resume"))
        self.button_log_analyser.setToolTip(_translate("Pokerbot", "Analyse past hands that the bot has played so you can improve the strategies"))
        self.button_log_analyser.setText(_translate("Pokerbot", "Strategy Analyser"))
        self.button_strategy_editor.setToolTip(_translate("Pokerbot", "Here you can edit strategies and adjust the bot to your needs"))
        self.button_strategy_editor.setText(_translate("Pokerbot", "Strategy Editor"))
        self.button_genetic_algorithm.setToolTip(_translate("Pokerbot", "<html><head/><body><p>An automatic algorithm that suggests what you need to change. It shows you at each stage whether you need to be more or less aggressive in calling, betting, bluffing etc.</p></body></html>"))
        self.button_genetic_algorithm.setText(_translate("Pokerbot", "Genetic Algorithm"))
        self.last_decision.setToolTip(_translate("Pokerbot", "Last made decision by the bot"))
        self.last_decision.setText(_translate("Pokerbot", "Last Decision"))
        self.comboBox_current_strategy.setToolTip(_translate("Pokerbot", "Choose the strategy that the bot should use to play"))
        self.status.setText(_translate("Pokerbot", "TextLabel"))
        self.progress_bar.setToolTip(_translate("Pokerbot", "Shows progress when the buttons appear"))
        self.equity.setToolTip(_translate("Pokerbot", "Winning probability as calculated by the simulation"))
        self.calllimit.setToolTip(_translate("Pokerbot", "The maximum amount on the call button where the bot would still call"))
        self.betlimit.setToolTip(_translate("Pokerbot", "The maximum amount on the bet button where the bot would still bet"))
        self.potsize.setToolTip(_translate("Pokerbot", "Pot size as show on the table"))
        self.gamenumber.setToolTip(_translate("Pokerbot", "How many hands have been played with the current strategy"))
        self.pushButton_help.setText(_translate("Pokerbot", "Help"))
        self.pushButton_setup.setToolTip(_translate("Pokerbot", "<html><head/><body><p>Setup which virtual machine the bot should access. You need to install Virtualbox to use this function (available for free). The pokerstars software will then run in the virtualbox and the pokerbot needs to run outside of the virtualbox.</p></body></html>"))
        self.pushButton_setup.setText(_translate("Pokerbot", "Setup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pokerbot = QtWidgets.QMainWindow()
    ui = Ui_Pokerbot()
    ui.setupUi(Pokerbot)
    Pokerbot.show()
    sys.exit(app.exec_())

