# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_table_setup.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_setup_form(object):
    def setupUi(self, table_setup_form):
        table_setup_form.setObjectName("table_setup_form")
        table_setup_form.resize(887, 962)
        self.scrollArea = QtWidgets.QScrollArea(table_setup_form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 590, 841, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 839, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.screenshot_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.screenshot_label.setText("")
        self.screenshot_label.setObjectName("screenshot_label")
        self.gridLayout.addWidget(self.screenshot_label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.crop = QtWidgets.QPushButton(table_setup_form)
        self.crop.setGeometry(QtCore.QRect(550, 310, 311, 41))
        self.crop.setObjectName("crop")
        self.topleft_corner = QtWidgets.QPushButton(table_setup_form)
        self.topleft_corner.setGeometry(QtCore.QRect(720, 280, 141, 21))
        self.topleft_corner.setObjectName("topleft_corner")
        self.tesseract = QtWidgets.QPushButton(table_setup_form)
        self.tesseract.setGeometry(QtCore.QRect(530, 400, 141, 31))
        self.tesseract.setObjectName("tesseract")
        self.take_screenshot_button = QtWidgets.QPushButton(table_setup_form)
        self.take_screenshot_button.setGeometry(QtCore.QRect(550, 180, 311, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.take_screenshot_button.setFont(font)
        self.take_screenshot_button.setObjectName("take_screenshot_button")
        self.label_3 = QtWidgets.QLabel(table_setup_form)
        self.label_3.setGeometry(QtCore.QRect(530, 440, 131, 16))
        self.label_3.setObjectName("label_3")
        self.tesseract_label = QtWidgets.QLabel(table_setup_form)
        self.tesseract_label.setGeometry(QtCore.QRect(670, 440, 47, 14))
        self.tesseract_label.setObjectName("tesseract_label")
        self.tabWidget = QtWidgets.QTabWidget(table_setup_form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 511, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 227, 321))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.raise_button = QtWidgets.QPushButton(self.groupBox)
        self.raise_button.setObjectName("raise_button")
        self.gridLayout_3.addWidget(self.raise_button, 2, 0, 1, 1)
        self.all_in_call_button = QtWidgets.QPushButton(self.groupBox)
        self.all_in_call_button.setObjectName("all_in_call_button")
        self.gridLayout_3.addWidget(self.all_in_call_button, 6, 0, 1, 1)
        self.buttons_search_area = QtWidgets.QPushButton(self.groupBox)
        self.buttons_search_area.setObjectName("buttons_search_area")
        self.gridLayout_3.addWidget(self.buttons_search_area, 0, 0, 1, 1)
        self.fold_button = QtWidgets.QPushButton(self.groupBox)
        self.fold_button.setObjectName("fold_button")
        self.gridLayout_3.addWidget(self.fold_button, 4, 0, 1, 1)
        self.im_back = QtWidgets.QPushButton(self.groupBox)
        self.im_back.setObjectName("im_back")
        self.gridLayout_3.addWidget(self.im_back, 11, 0, 1, 1)
        self.lost_everything = QtWidgets.QPushButton(self.groupBox)
        self.lost_everything.setObjectName("lost_everything")
        self.gridLayout_3.addWidget(self.lost_everything, 10, 0, 1, 1)
        self.check_button = QtWidgets.QPushButton(self.groupBox)
        self.check_button.setObjectName("check_button")
        self.gridLayout_3.addWidget(self.check_button, 3, 0, 1, 1)
        self.call_button = QtWidgets.QPushButton(self.groupBox)
        self.call_button.setObjectName("call_button")
        self.gridLayout_3.addWidget(self.call_button, 1, 0, 1, 1)
        self.my_turn = QtWidgets.QPushButton(self.groupBox)
        self.my_turn.setObjectName("my_turn")
        self.gridLayout_3.addWidget(self.my_turn, 8, 0, 1, 1)
        self.my_turn_search_area = QtWidgets.QPushButton(self.groupBox)
        self.my_turn_search_area.setObjectName("my_turn_search_area")
        self.gridLayout_3.addWidget(self.my_turn_search_area, 7, 0, 1, 1)
        self.lost_everything_search_area = QtWidgets.QPushButton(self.groupBox)
        self.lost_everything_search_area.setObjectName("lost_everything_search_area")
        self.gridLayout_3.addWidget(self.lost_everything_search_area, 9, 0, 1, 1)
        self.fast_fold_button = QtWidgets.QPushButton(self.groupBox)
        self.fast_fold_button.setObjectName("fast_fold_button")
        self.gridLayout_3.addWidget(self.fast_fold_button, 5, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(260, 30, 223, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.my_cards_area = QtWidgets.QPushButton(self.groupBox_6)
        self.my_cards_area.setObjectName("my_cards_area")
        self.verticalLayout_4.addWidget(self.my_cards_area)
        self.table_cards_area = QtWidgets.QPushButton(self.groupBox_6)
        self.table_cards_area.setObjectName("table_cards_area")
        self.verticalLayout_4.addWidget(self.table_cards_area)
        self.total_pot_area = QtWidgets.QPushButton(self.groupBox_6)
        self.total_pot_area.setObjectName("total_pot_area")
        self.verticalLayout_4.addWidget(self.total_pot_area)
        self.current_round_pot = QtWidgets.QPushButton(self.groupBox_6)
        self.current_round_pot.setObjectName("current_round_pot")
        self.verticalLayout_4.addWidget(self.current_round_pot)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 230, 201, 112))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.raise_value = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.raise_value.setFlat(False)
        self.raise_value.setObjectName("raise_value")
        self.verticalLayout_3.addWidget(self.raise_value)
        self.call_value = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.call_value.setObjectName("call_value")
        self.verticalLayout_3.addWidget(self.call_value)
        self.all_in_call_value = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.all_in_call_value.setObjectName("all_in_call_value")
        self.verticalLayout_3.addWidget(self.all_in_call_value)
        self.game_number = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.game_number.setObjectName("game_number")
        self.verticalLayout_3.addWidget(self.game_number)
        self.tabWidget.addTab(self.tab_2, "")
        self.players_tab = QtWidgets.QWidget()
        self.players_tab.setObjectName("players_tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.players_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 40, 371, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.max_players = QtWidgets.QComboBox(self.groupBox_3)
        self.max_players.setGeometry(QtCore.QRect(10, 20, 91, 22))
        self.max_players.setObjectName("max_players")
        self.max_players.addItem("")
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.player_funds_area = QtWidgets.QPushButton(self.groupBox_2)
        self.player_funds_area.setObjectName("player_funds_area")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.player_funds_area)
        self.player_pot_area = QtWidgets.QPushButton(self.groupBox_2)
        self.player_pot_area.setObjectName("player_pot_area")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.player_pot_area)
        self.player_name_area = QtWidgets.QPushButton(self.groupBox_2)
        self.player_name_area.setObjectName("player_name_area")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.player_name_area)
        self.covered_card_area = QtWidgets.QPushButton(self.groupBox_2)
        self.covered_card_area.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.covered_card_area.setToolTipDuration(9)
        self.covered_card_area.setObjectName("covered_card_area")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.covered_card_area)
        self.button_search_area = QtWidgets.QPushButton(self.groupBox_2)
        self.button_search_area.setObjectName("button_search_area")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.button_search_area)
        self.gridLayout_5.addLayout(self.formLayout_2, 0, 1, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.current_player = QtWidgets.QComboBox(self.groupBox_4)
        self.current_player.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.current_player.setObjectName("current_player")
        self.current_player.addItem("")
        self.current_player.addItem("")
        self.current_player.addItem("")
        self.current_player.addItem("")
        self.current_player.addItem("")
        self.current_player.addItem("")
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.players_tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 491, 261))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.card_ah = QtWidgets.QPushButton(self.groupBox_5)
        self.card_ah.setObjectName("card_ah")
        self.horizontalLayout_10.addWidget(self.card_ah)
        self.card_kh = QtWidgets.QPushButton(self.groupBox_5)
        self.card_kh.setObjectName("card_kh")
        self.horizontalLayout_10.addWidget(self.card_kh)
        self.card_qh = QtWidgets.QPushButton(self.groupBox_5)
        self.card_qh.setObjectName("card_qh")
        self.horizontalLayout_10.addWidget(self.card_qh)
        self.card_jh = QtWidgets.QPushButton(self.groupBox_5)
        self.card_jh.setObjectName("card_jh")
        self.horizontalLayout_10.addWidget(self.card_jh)
        self.card_th = QtWidgets.QPushButton(self.groupBox_5)
        self.card_th.setObjectName("card_th")
        self.horizontalLayout_10.addWidget(self.card_th)
        self.card_9h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_9h.setObjectName("card_9h")
        self.horizontalLayout_10.addWidget(self.card_9h)
        self.card_8h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_8h.setObjectName("card_8h")
        self.horizontalLayout_10.addWidget(self.card_8h)
        self.card_7h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_7h.setObjectName("card_7h")
        self.horizontalLayout_10.addWidget(self.card_7h)
        self.card_6h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_6h.setObjectName("card_6h")
        self.horizontalLayout_10.addWidget(self.card_6h)
        self.card_5h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_5h.setObjectName("card_5h")
        self.horizontalLayout_10.addWidget(self.card_5h)
        self.card_4h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_4h.setObjectName("card_4h")
        self.horizontalLayout_10.addWidget(self.card_4h)
        self.card_3h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_3h.setObjectName("card_3h")
        self.horizontalLayout_10.addWidget(self.card_3h)
        self.card_2h = QtWidgets.QPushButton(self.groupBox_5)
        self.card_2h.setObjectName("card_2h")
        self.horizontalLayout_10.addWidget(self.card_2h)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.card_as = QtWidgets.QPushButton(self.groupBox_5)
        self.card_as.setObjectName("card_as")
        self.horizontalLayout_2.addWidget(self.card_as)
        self.card_ks = QtWidgets.QPushButton(self.groupBox_5)
        self.card_ks.setObjectName("card_ks")
        self.horizontalLayout_2.addWidget(self.card_ks)
        self.card_qs = QtWidgets.QPushButton(self.groupBox_5)
        self.card_qs.setObjectName("card_qs")
        self.horizontalLayout_2.addWidget(self.card_qs)
        self.card_js = QtWidgets.QPushButton(self.groupBox_5)
        self.card_js.setObjectName("card_js")
        self.horizontalLayout_2.addWidget(self.card_js)
        self.card_ts = QtWidgets.QPushButton(self.groupBox_5)
        self.card_ts.setObjectName("card_ts")
        self.horizontalLayout_2.addWidget(self.card_ts)
        self.card_9s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_9s.setObjectName("card_9s")
        self.horizontalLayout_2.addWidget(self.card_9s)
        self.card_8s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_8s.setObjectName("card_8s")
        self.horizontalLayout_2.addWidget(self.card_8s)
        self.card_7s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_7s.setObjectName("card_7s")
        self.horizontalLayout_2.addWidget(self.card_7s)
        self.card_6s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_6s.setObjectName("card_6s")
        self.horizontalLayout_2.addWidget(self.card_6s)
        self.card_5s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_5s.setObjectName("card_5s")
        self.horizontalLayout_2.addWidget(self.card_5s)
        self.card_4s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_4s.setObjectName("card_4s")
        self.horizontalLayout_2.addWidget(self.card_4s)
        self.card_3s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_3s.setObjectName("card_3s")
        self.horizontalLayout_2.addWidget(self.card_3s)
        self.card_2s = QtWidgets.QPushButton(self.groupBox_5)
        self.card_2s.setObjectName("card_2s")
        self.horizontalLayout_2.addWidget(self.card_2s)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.card_ad = QtWidgets.QPushButton(self.groupBox_5)
        self.card_ad.setObjectName("card_ad")
        self.horizontalLayout_9.addWidget(self.card_ad)
        self.card_kd = QtWidgets.QPushButton(self.groupBox_5)
        self.card_kd.setObjectName("card_kd")
        self.horizontalLayout_9.addWidget(self.card_kd)
        self.card_qd = QtWidgets.QPushButton(self.groupBox_5)
        self.card_qd.setObjectName("card_qd")
        self.horizontalLayout_9.addWidget(self.card_qd)
        self.card_jd = QtWidgets.QPushButton(self.groupBox_5)
        self.card_jd.setObjectName("card_jd")
        self.horizontalLayout_9.addWidget(self.card_jd)
        self.card_td = QtWidgets.QPushButton(self.groupBox_5)
        self.card_td.setObjectName("card_td")
        self.horizontalLayout_9.addWidget(self.card_td)
        self.card_9d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_9d.setObjectName("card_9d")
        self.horizontalLayout_9.addWidget(self.card_9d)
        self.card_8d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_8d.setObjectName("card_8d")
        self.horizontalLayout_9.addWidget(self.card_8d)
        self.card_7d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_7d.setObjectName("card_7d")
        self.horizontalLayout_9.addWidget(self.card_7d)
        self.card_6d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_6d.setObjectName("card_6d")
        self.horizontalLayout_9.addWidget(self.card_6d)
        self.card_5d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_5d.setObjectName("card_5d")
        self.horizontalLayout_9.addWidget(self.card_5d)
        self.card_4d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_4d.setObjectName("card_4d")
        self.horizontalLayout_9.addWidget(self.card_4d)
        self.card_3d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_3d.setObjectName("card_3d")
        self.horizontalLayout_9.addWidget(self.card_3d)
        self.card_2d = QtWidgets.QPushButton(self.groupBox_5)
        self.card_2d.setObjectName("card_2d")
        self.horizontalLayout_9.addWidget(self.card_2d)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.card_ac = QtWidgets.QPushButton(self.groupBox_5)
        self.card_ac.setObjectName("card_ac")
        self.horizontalLayout_8.addWidget(self.card_ac)
        self.card_kc = QtWidgets.QPushButton(self.groupBox_5)
        self.card_kc.setObjectName("card_kc")
        self.horizontalLayout_8.addWidget(self.card_kc)
        self.card_qc = QtWidgets.QPushButton(self.groupBox_5)
        self.card_qc.setObjectName("card_qc")
        self.horizontalLayout_8.addWidget(self.card_qc)
        self.card_jc = QtWidgets.QPushButton(self.groupBox_5)
        self.card_jc.setObjectName("card_jc")
        self.horizontalLayout_8.addWidget(self.card_jc)
        self.card_tc = QtWidgets.QPushButton(self.groupBox_5)
        self.card_tc.setObjectName("card_tc")
        self.horizontalLayout_8.addWidget(self.card_tc)
        self.card_9c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_9c.setObjectName("card_9c")
        self.horizontalLayout_8.addWidget(self.card_9c)
        self.card_8c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_8c.setObjectName("card_8c")
        self.horizontalLayout_8.addWidget(self.card_8c)
        self.card_7c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_7c.setObjectName("card_7c")
        self.horizontalLayout_8.addWidget(self.card_7c)
        self.card_6c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_6c.setObjectName("card_6c")
        self.horizontalLayout_8.addWidget(self.card_6c)
        self.card_5c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_5c.setObjectName("card_5c")
        self.horizontalLayout_8.addWidget(self.card_5c)
        self.card_4c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_4c.setObjectName("card_4c")
        self.horizontalLayout_8.addWidget(self.card_4c)
        self.card_3c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_3c.setObjectName("card_3c")
        self.horizontalLayout_8.addWidget(self.card_3c)
        self.card_2c = QtWidgets.QPushButton(self.groupBox_5)
        self.card_2c.setObjectName("card_2c")
        self.horizontalLayout_8.addWidget(self.card_2c)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dealer_button = QtWidgets.QPushButton(self.groupBox_5)
        self.dealer_button.setObjectName("dealer_button")
        self.horizontalLayout.addWidget(self.dealer_button)
        self.covered_card = QtWidgets.QPushButton(self.groupBox_5)
        self.covered_card.setObjectName("covered_card")
        self.horizontalLayout.addWidget(self.covered_card)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 401, 121))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mouse_fast_fold = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_fast_fold.setObjectName("mouse_fast_fold")
        self.gridLayout_2.addWidget(self.mouse_fast_fold, 1, 2, 1, 1)
        self.mouse_full_pot = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_full_pot.setObjectName("mouse_full_pot")
        self.gridLayout_2.addWidget(self.mouse_full_pot, 0, 3, 1, 1)
        self.mouse_call = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_call.setObjectName("mouse_call")
        self.gridLayout_2.addWidget(self.mouse_call, 1, 0, 1, 1)
        self.mouse_raise = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_raise.setObjectName("mouse_raise")
        self.gridLayout_2.addWidget(self.mouse_raise, 0, 1, 1, 1)
        self.mouse_call2 = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_call2.setObjectName("mouse_call2")
        self.gridLayout_2.addWidget(self.mouse_call2, 1, 1, 1, 1)
        self.mouse_fold = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_fold.setObjectName("mouse_fold")
        self.gridLayout_2.addWidget(self.mouse_fold, 0, 0, 1, 1)
        self.mouse_all_in = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_all_in.setObjectName("mouse_all_in")
        self.gridLayout_2.addWidget(self.mouse_all_in, 1, 3, 1, 1)
        self.mouse_half_pot = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_half_pot.setObjectName("mouse_half_pot")
        self.gridLayout_2.addWidget(self.mouse_half_pot, 0, 2, 1, 1)
        self.mouse_imback = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_imback.setObjectName("mouse_imback")
        self.gridLayout_2.addWidget(self.mouse_imback, 2, 1, 1, 1)
        self.mouse_check = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_check.setObjectName("mouse_check")
        self.gridLayout_2.addWidget(self.mouse_check, 2, 0, 1, 1)
        self.mouse_increase = QtWidgets.QPushButton(self.groupBox_8)
        self.mouse_increase.setObjectName("mouse_increase")
        self.gridLayout_2.addWidget(self.mouse_increase, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.test_all_button = QtWidgets.QPushButton(self.tab)
        self.test_all_button.setGeometry(QtCore.QRect(20, 80, 371, 81))
        self.test_all_button.setObjectName("test_all_button")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 441, 16))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.groupBox_7 = QtWidgets.QGroupBox(table_setup_form)
        self.groupBox_7.setGeometry(QtCore.QRect(520, 0, 351, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.load = QtWidgets.QPushButton(self.groupBox_7)
        self.load.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.load.setObjectName("load")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(0, 10, 61, 20))
        self.label.setObjectName("label")
        self.table_name = QtWidgets.QComboBox(self.groupBox_7)
        self.table_name.setGeometry(QtCore.QRect(0, 30, 281, 22))
        self.table_name.setObjectName("table_name")
        self.button_delete = QtWidgets.QPushButton(self.groupBox_7)
        self.button_delete.setGeometry(QtCore.QRect(110, 60, 91, 23))
        self.button_delete.setObjectName("button_delete")
        self.load_topleft_corner = QtWidgets.QPushButton(table_setup_form)
        self.load_topleft_corner.setGeometry(QtCore.QRect(550, 230, 311, 41))
        self.load_topleft_corner.setObjectName("load_topleft_corner")
        self.scrollArea_2 = QtWidgets.QScrollArea(table_setup_form)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 460, 841, 81))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 839, 79))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.preview_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.preview_label.setText("")
        self.preview_label.setObjectName("preview_label")
        self.horizontalLayout_3.addWidget(self.preview_label)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(table_setup_form)
        self.label_2.setGeometry(QtCore.QRect(530, 180, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(table_setup_form)
        self.label_8.setGeometry(QtCore.QRect(530, 230, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(table_setup_form)
        self.label_9.setGeometry(QtCore.QRect(530, 320, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(table_setup_form)
        self.label_11.setGeometry(QtCore.QRect(530, 370, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(table_setup_form)
        self.label_10.setGeometry(QtCore.QRect(150, 20, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(table_setup_form)
        self.label_13.setGeometry(QtCore.QRect(530, 160, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(table_setup_form)
        self.label_14.setGeometry(QtCore.QRect(600, 160, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(table_setup_form)
        self.label_12.setGeometry(QtCore.QRect(470, 0, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.groupBox_9 = QtWidgets.QGroupBox(table_setup_form)
        self.groupBox_9.setGeometry(QtCore.QRect(520, 90, 351, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.blank_new = QtWidgets.QPushButton(self.groupBox_9)
        self.blank_new.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.blank_new.setObjectName("blank_new")
        self.copy_to_new = QtWidgets.QPushButton(self.groupBox_9)
        self.copy_to_new.setGeometry(QtCore.QRect(100, 40, 71, 23))
        self.copy_to_new.setObjectName("copy_to_new")
        self.new_name = QtWidgets.QLineEdit(self.groupBox_9)
        self.new_name.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.new_name.setObjectName("new_name")
        self.label_15 = QtWidgets.QLabel(table_setup_form)
        self.label_15.setGeometry(QtCore.QRect(20, 570, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(table_setup_form)
        self.label_16.setGeometry(QtCore.QRect(20, 440, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(table_setup_form)
        self.label_17.setGeometry(QtCore.QRect(140, 570, 601, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(table_setup_form)
        self.label_18.setGeometry(QtCore.QRect(530, 380, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(table_setup_form)
        self.label_5.setGeometry(QtCore.QRect(550, 280, 171, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(table_setup_form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(table_setup_form)

    def retranslateUi(self, table_setup_form):
        _translate = QtCore.QCoreApplication.translate
        table_setup_form.setWindowTitle(_translate("table_setup_form", "Form"))
        self.crop.setToolTip(_translate("table_setup_form", "Crops the image to only show everything relative to the top left corner."))
        self.crop.setText(_translate("table_setup_form", "Crop from top left corner"))
        self.topleft_corner.setToolTip(_translate("table_setup_form", "<html><head/><body><p>After selecting the top left corner (usually the poker sign at the top left of the windows window). It is used as a refernece point to find the poker window. CAREFUL: If you change the top left corner, all subsequent locations need to entered again!</p></body></html>"))
        self.topleft_corner.setText(_translate("table_setup_form", "Save new top left corner"))
        self.tesseract.setToolTip(_translate("table_setup_form", "Tries to use OCR on the last marked location to see if a number of name can be correctly recognized"))
        self.tesseract.setText(_translate("table_setup_form", "Recognize number"))
        self.take_screenshot_button.setToolTip(_translate("table_setup_form", "Takes a screenshot of the entire screen. This is the first step you need to take"))
        self.take_screenshot_button.setText(_translate("table_setup_form", "Take screenshot"))
        self.label_3.setText(_translate("table_setup_form", "Tesseract recognition"))
        self.tesseract_label.setText(_translate("table_setup_form", "na"))
        self.groupBox.setTitle(_translate("table_setup_form", "Button Images and value areas"))
        self.raise_button.setToolTip(_translate("table_setup_form", "Only select the raise text, without the chainging element of the raise amount"))
        self.raise_button.setText(_translate("table_setup_form", "Raise Button"))
        self.all_in_call_button.setToolTip(_translate("table_setup_form", "Ensure to only select the portion that never changes"))
        self.all_in_call_button.setText(_translate("table_setup_form", "All in call Button"))
        self.buttons_search_area.setToolTip(_translate("table_setup_form", "Area where fold, call and raise buttons are located"))
        self.buttons_search_area.setText(_translate("table_setup_form", "Buttons search area"))
        self.fold_button.setText(_translate("table_setup_form", "Fold Button"))
        self.im_back.setToolTip(_translate("table_setup_form", "Image showing I\'m back, in case of tha time out"))
        self.im_back.setText(_translate("table_setup_form", "I\'m back"))
        self.lost_everything.setToolTip(_translate("table_setup_form", "An image showing no funds left: e.g. 0.00"))
        self.lost_everything.setText(_translate("table_setup_form", "Lost everything image"))
        self.check_button.setText(_translate("table_setup_form", "Check Button"))
        self.call_button.setToolTip(_translate("table_setup_form", "Only select a small portion of the button (e.g. the call text), without the actual call amount"))
        self.call_button.setText(_translate("table_setup_form", "Call Button"))
        self.my_turn.setToolTip(_translate("table_setup_form", "Best select the top left corner of the call button, or any other element that is always identical for all situations when it\'s your turn"))
        self.my_turn.setText(_translate("table_setup_form", "\"My Turn\" image"))
        self.my_turn_search_area.setToolTip(_translate("table_setup_form", "Select an area where to look for a single sign that it\'s your turn"))
        self.my_turn_search_area.setText(_translate("table_setup_form", "\"My turn\" search area"))
        self.lost_everything_search_area.setToolTip(_translate("table_setup_form", "Select area to look for a sign that all funds are lost. This is usually the area of the player\'s left funds."))
        self.lost_everything_search_area.setText(_translate("table_setup_form", "Lost everything search area"))
        self.fast_fold_button.setText(_translate("table_setup_form", "Fast Fold Button"))
        self.groupBox_6.setTitle(_translate("table_setup_form", "Search Areas"))
        self.my_cards_area.setToolTip(_translate("table_setup_form", "Area where the player holds his cards"))
        self.my_cards_area.setText(_translate("table_setup_form", "My Cards area"))
        self.table_cards_area.setToolTip(_translate("table_setup_form", "Area where the cards appear on the table at flop, turn and river"))
        self.table_cards_area.setText(_translate("table_setup_form", "Table Cards Area"))
        self.total_pot_area.setToolTip(_translate("table_setup_form", "Total pot. Make sure to only select the numbers very narrowly and test it by pressing the recognize number or text button"))
        self.total_pot_area.setText(_translate("table_setup_form", "Total Pot Area"))
        self.current_round_pot.setToolTip(_translate("table_setup_form", "The pot of the current rount (e.g. flop). Select the area very narrowly and test it by pressing the recognize number button"))
        self.current_round_pot.setText(_translate("table_setup_form", "Current Round Pot"))
        self.raise_value.setToolTip(_translate("table_setup_form", "The value on the raise button. Make sure to select very narrowly and then test with the recognize number button"))
        self.raise_value.setText(_translate("table_setup_form", "Raise Value"))
        self.call_value.setToolTip(_translate("table_setup_form", "Value on the call button, make sure to select narrowly and then test by pressing the recognize number button"))
        self.call_value.setText(_translate("table_setup_form", "Call value"))
        self.all_in_call_value.setToolTip(_translate("table_setup_form", "The all in call value may be in a different place in case the all in call button appears. Make sure to select the value narrowly and test it with the recognize number button"))
        self.all_in_call_value.setText(_translate("table_setup_form", "All in call value"))
        self.game_number.setToolTip(_translate("table_setup_form", "Game number for collusion, in partypoker available on top right"))
        self.game_number.setText(_translate("table_setup_form", "Game Number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("table_setup_form", "Buttons and search areas"))
        self.groupBox_2.setTitle(_translate("table_setup_form", "Players"))
        self.groupBox_3.setTitle(_translate("table_setup_form", "Table size"))
        self.max_players.setToolTip(_translate("table_setup_form", "Select the amount of players on the table"))
        self.max_players.setItemText(0, _translate("table_setup_form", "6"))
        self.player_funds_area.setToolTip(_translate("table_setup_form", "area where the remaining player funds are shown. Use narrow selection and test it by pressing the Recognize number button"))
        self.player_funds_area.setText(_translate("table_setup_form", "Player funds area"))
        self.player_pot_area.setToolTip(_translate("table_setup_form", "Pot of the player"))
        self.player_pot_area.setText(_translate("table_setup_form", "Player pot area"))
        self.player_name_area.setText(_translate("table_setup_form", "Player name area"))
        self.covered_card_area.setToolTip(_translate("table_setup_form", "Area where the player has the cards, so the bot can detect if he is still in the game"))
        self.covered_card_area.setText(_translate("table_setup_form", "Covered card area"))
        self.button_search_area.setToolTip(_translate("table_setup_form", "Where the given player would have the button to indicate he is the dealer. "))
        self.button_search_area.setText(_translate("table_setup_form", "Button search area"))
        self.groupBox_4.setTitle(_translate("table_setup_form", "Player (0=myself)"))
        self.current_player.setToolTip(_translate("table_setup_form", "0 is the bot, then counter clockwise the other players"))
        self.current_player.setItemText(0, _translate("table_setup_form", "0"))
        self.current_player.setItemText(1, _translate("table_setup_form", "1"))
        self.current_player.setItemText(2, _translate("table_setup_form", "2"))
        self.current_player.setItemText(3, _translate("table_setup_form", "3"))
        self.current_player.setItemText(4, _translate("table_setup_form", "4"))
        self.current_player.setItemText(5, _translate("table_setup_form", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.players_tab), _translate("table_setup_form", "Players"))
        self.groupBox_5.setToolTip(_translate("table_setup_form", "Ensure to mark as narrowly as possible. Don\'t mark the full card, but only the number and the symbol."))
        self.groupBox_5.setTitle(_translate("table_setup_form", "Images"))
        self.card_ah.setText(_translate("table_setup_form", "AH"))
        self.card_kh.setText(_translate("table_setup_form", "KH"))
        self.card_qh.setText(_translate("table_setup_form", "QH"))
        self.card_jh.setText(_translate("table_setup_form", "JH"))
        self.card_th.setText(_translate("table_setup_form", "TH"))
        self.card_9h.setText(_translate("table_setup_form", "9H"))
        self.card_8h.setText(_translate("table_setup_form", "8H"))
        self.card_7h.setText(_translate("table_setup_form", "7H"))
        self.card_6h.setText(_translate("table_setup_form", "6H"))
        self.card_5h.setText(_translate("table_setup_form", "5H"))
        self.card_4h.setText(_translate("table_setup_form", "4H"))
        self.card_3h.setText(_translate("table_setup_form", "3H"))
        self.card_2h.setText(_translate("table_setup_form", "2H"))
        self.card_as.setText(_translate("table_setup_form", "AS"))
        self.card_ks.setText(_translate("table_setup_form", "KS"))
        self.card_qs.setText(_translate("table_setup_form", "QS"))
        self.card_js.setText(_translate("table_setup_form", "JS"))
        self.card_ts.setText(_translate("table_setup_form", "TS"))
        self.card_9s.setText(_translate("table_setup_form", "9S"))
        self.card_8s.setText(_translate("table_setup_form", "8S"))
        self.card_7s.setText(_translate("table_setup_form", "7S"))
        self.card_6s.setText(_translate("table_setup_form", "6S"))
        self.card_5s.setText(_translate("table_setup_form", "5S"))
        self.card_4s.setText(_translate("table_setup_form", "4S"))
        self.card_3s.setText(_translate("table_setup_form", "3S"))
        self.card_2s.setText(_translate("table_setup_form", "2S"))
        self.card_ad.setText(_translate("table_setup_form", "AD"))
        self.card_kd.setText(_translate("table_setup_form", "KD"))
        self.card_qd.setText(_translate("table_setup_form", "QD"))
        self.card_jd.setText(_translate("table_setup_form", "JD"))
        self.card_td.setText(_translate("table_setup_form", "TD"))
        self.card_9d.setText(_translate("table_setup_form", "9D"))
        self.card_8d.setText(_translate("table_setup_form", "8D"))
        self.card_7d.setText(_translate("table_setup_form", "7D"))
        self.card_6d.setText(_translate("table_setup_form", "6D"))
        self.card_5d.setText(_translate("table_setup_form", "5D"))
        self.card_4d.setText(_translate("table_setup_form", "4D"))
        self.card_3d.setText(_translate("table_setup_form", "3D"))
        self.card_2d.setText(_translate("table_setup_form", "2D"))
        self.card_ac.setText(_translate("table_setup_form", "AC"))
        self.card_kc.setText(_translate("table_setup_form", "KC"))
        self.card_qc.setText(_translate("table_setup_form", "QC"))
        self.card_jc.setText(_translate("table_setup_form", "JC"))
        self.card_tc.setText(_translate("table_setup_form", "TC"))
        self.card_9c.setText(_translate("table_setup_form", "9C"))
        self.card_8c.setText(_translate("table_setup_form", "8C"))
        self.card_7c.setText(_translate("table_setup_form", "7C"))
        self.card_6c.setText(_translate("table_setup_form", "6C"))
        self.card_5c.setText(_translate("table_setup_form", "5C"))
        self.card_4c.setText(_translate("table_setup_form", "4C"))
        self.card_3c.setText(_translate("table_setup_form", "3C"))
        self.card_2c.setText(_translate("table_setup_form", "2C"))
        self.dealer_button.setToolTip(_translate("table_setup_form", "The dealer button image. Make sure to select very narrowly and don\'t include any background that might change depending on it\'s location"))
        self.dealer_button.setText(_translate("table_setup_form", "Dealer button"))
        self.covered_card.setToolTip(_translate("table_setup_form", "Used to recognize which players are still in the game. Mark very narrowly to ensure it\'s the same for all players."))
        self.covered_card.setText(_translate("table_setup_form", "Covered card"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("table_setup_form", "Cards"))
        self.groupBox_8.setTitle(_translate("table_setup_form", "Mouse Control"))
        self.mouse_fast_fold.setText(_translate("table_setup_form", "Fast Fold"))
        self.mouse_full_pot.setText(_translate("table_setup_form", "Full pot"))
        self.mouse_call.setText(_translate("table_setup_form", "Call"))
        self.mouse_raise.setText(_translate("table_setup_form", "Raise"))
        self.mouse_call2.setToolTip(_translate("table_setup_form", "Location of call button if no raise can be made (usally the same as normal call button, except for Pokerstars it is at the place of the raise button)"))
        self.mouse_call2.setText(_translate("table_setup_form", "Call2"))
        self.mouse_fold.setToolTip(_translate("table_setup_form", "Area of fold button to click"))
        self.mouse_fold.setText(_translate("table_setup_form", "Fold"))
        self.mouse_all_in.setText(_translate("table_setup_form", "All In"))
        self.mouse_half_pot.setText(_translate("table_setup_form", "Half pot"))
        self.mouse_imback.setToolTip(_translate("table_setup_form", "Location of I\'m back button"))
        self.mouse_imback.setText(_translate("table_setup_form", "I\'m back"))
        self.mouse_check.setToolTip(_translate("table_setup_form", "Location of I\'m back button"))
        self.mouse_check.setText(_translate("table_setup_form", "Check"))
        self.mouse_increase.setText(_translate("table_setup_form", "Increase"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("table_setup_form", "Mouse Targets"))
        self.test_all_button.setToolTip(_translate("table_setup_form", "Reads the table as per taken screenshot (use take screenshot button) and displays the results in the below box. That way you can see if further changes are necessary."))
        self.test_all_button.setText(_translate("table_setup_form", "Test all"))
        self.label_4.setText(_translate("table_setup_form", "Take a screenshot and press Test all. Then check the console output for error messages."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("table_setup_form", "Test"))
        self.groupBox_7.setTitle(_translate("table_setup_form", "Load Template for editing"))
        self.load.setToolTip(_translate("table_setup_form", "Load the template to show which items have already been learned. They can still be overwritten by simply marking the area or image and then pressing the corresponding butotn."))
        self.load.setText(_translate("table_setup_form", "Load template"))
        self.label.setText(_translate("table_setup_form", "Table name"))
        self.table_name.setToolTip(_translate("table_setup_form", "Select a table to edit. You can only edit your own tables. To edit take a screenshot, crop it with the cop left corner, then select the area top left and bottom right and then choose the corresponding button"))
        self.button_delete.setToolTip(_translate("table_setup_form", "Load the template to show which items have already been learned. They can still be overwritten by simply marking the area or image and then pressing the corresponding butotn."))
        self.button_delete.setText(_translate("table_setup_form", "delete"))
        self.load_topleft_corner.setToolTip(_translate("table_setup_form", "Loads a previously saved top left corner"))
        self.load_topleft_corner.setText(_translate("table_setup_form", "Load top left corner"))
        self.label_2.setText(_translate("table_setup_form", "1"))
        self.label_8.setText(_translate("table_setup_form", "2"))
        self.label_9.setText(_translate("table_setup_form", "3"))
        self.label_11.setText(_translate("table_setup_form", "Step 6 (only for numbers, optional)"))
        self.label_10.setText(_translate("table_setup_form", "Step 5. Assign selection to save it"))
        self.label_13.setText(_translate("table_setup_form", "Steps"))
        self.label_14.setText(_translate("table_setup_form", "Ensure poker table is visible"))
        self.label_12.setText(_translate("table_setup_form", "Step 0"))
        self.groupBox_9.setTitle(_translate("table_setup_form", "Create a new template, USE GOOD NAMING OR IT WILL BE DELETED!!"))
        self.blank_new.setToolTip(_translate("table_setup_form", "Create a new blank template"))
        self.blank_new.setText(_translate("table_setup_form", "blank new"))
        self.copy_to_new.setToolTip(_translate("table_setup_form", "Take current template and create a new one that you can then edit"))
        self.copy_to_new.setText(_translate("table_setup_form", "copy to new"))
        self.label_15.setText(_translate("table_setup_form", "Full screenshot"))
        self.label_16.setText(_translate("table_setup_form", "Selection after clicking top left and bottom right of below screenshot"))
        self.label_17.setText(_translate("table_setup_form", "Step 4: click on top left and bottom right (2 separate clicks) of what you want to select"))
        self.label_18.setText(_translate("table_setup_form", "Check if recognition works correctly"))
        self.label_5.setText(_translate("table_setup_form", "Only do this once at the beginning:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_setup_form = QtWidgets.QWidget()
    ui = Ui_table_setup_form()
    ui.setupUi(table_setup_form)
    table_setup_form.show()
    sys.exit(app.exec_())
