name: Windows Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Tesseract
        run: |
          iwr https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.6.0-tesseract-5.3.1/tesserocr-2.6.0-cp311-cp311-win_amd64.whl -Out tesserocr-2.6.0-cp311-cp311-win_amd64.whl
          pip install tesserocr-2.6.0-cp311-cp311-win_amd64.whl

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          cd poker
          pyinstaller main.spec
          # Add other necessary steps here

      - name: Install NSIS
        run: |
          choco install nsis

      - name: Run NSIS
        run: makensis -V3 DeepMindPokerbot.nsi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-app
          path: path/to/your/compiled/app
